version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

formatters:
  enable:
    - gofmt
    - goimports
