// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, email, password_hash)
VALUES ($1, $2, $3)
`

type CreateAccountParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, account_id, public_id)
VALUES ($1, $2, $3)
`

type CreatePlayerParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	PublicID  string      `json:"public_id"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.Exec(ctx, createPlayer, arg.ID, arg.AccountID, arg.PublicID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, account_id, player_id, token_digest, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateSessionParams struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	TokenDigest []byte             `json:"token_digest"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.PlayerID,
		arg.TokenDigest,
		arg.ExpiresAt,
	)
	return err
}

const getAccountForLogin = `-- name: GetAccountForLogin :one
SELECT
    a.id AS account_id,
    p.id AS player_id,
    a.password_hash
FROM accounts AS a
JOIN players AS p
    ON p.account_id = a.id
WHERE a.email = $1
  AND a.status = 'ACTIVE'
`

type GetAccountForLoginRow struct {
	AccountID    pgtype.UUID `json:"account_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetAccountForLogin(ctx context.Context, email string) (GetAccountForLoginRow, error) {
	row := q.db.QueryRow(ctx, getAccountForLogin, email)
	var i GetAccountForLoginRow
	err := row.Scan(&i.AccountID, &i.PlayerID, &i.PasswordHash)
	return i, err
}
