// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: content.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContentReleaseRows = `-- name: CountContentReleaseRows :one
SELECT
    (SELECT count(*) FROM basket_mapping_versions AS b WHERE b.content_version = $1)::bigint AS basket_mapping_count,
    (SELECT count(*) FROM keeper_definition_versions AS k WHERE k.content_version = $1)::bigint AS keeper_definition_count,
    (SELECT count(*)
     FROM basket_mapping_components AS c
     JOIN basket_mapping_versions AS b ON b.id = c.basket_mapping_version_id
     WHERE b.content_version = $1)::bigint AS component_count,
    (SELECT count(*)
     FROM keeper_definition_upgrade_nodes AS n
     JOIN keeper_definition_versions AS k ON k.id = n.keeper_definition_version_id
     WHERE k.content_version = $1)::bigint AS node_count,
    (SELECT count(*) FROM strategy_definition_versions AS s WHERE s.content_version = $1)::bigint AS strategy_count,
    (SELECT count(*) FROM relic_definition_versions AS r WHERE r.content_version = $1)::bigint AS relic_count,
    (SELECT count(*) FROM synergy_definition_versions AS s WHERE s.content_version = $1)::bigint AS synergy_count,
    (SELECT count(*) FROM daily_modifier_definition_versions AS m WHERE m.content_version = $1)::bigint AS modifier_count,
    (SELECT count(*) FROM daily_objective_definition_versions AS o WHERE o.content_version = $1)::bigint AS objective_count,
    (SELECT count(*) FROM game_rule_set_versions AS g WHERE g.content_version = $1)::bigint AS game_rule_set_count
`

type CountContentReleaseRowsRow struct {
	BasketMappingCount    int64 `json:"basket_mapping_count"`
	KeeperDefinitionCount int64 `json:"keeper_definition_count"`
	ComponentCount        int64 `json:"component_count"`
	NodeCount             int64 `json:"node_count"`
	StrategyCount         int64 `json:"strategy_count"`
	RelicCount            int64 `json:"relic_count"`
	SynergyCount          int64 `json:"synergy_count"`
	ModifierCount         int64 `json:"modifier_count"`
	ObjectiveCount        int64 `json:"objective_count"`
	GameRuleSetCount      int64 `json:"game_rule_set_count"`
}

func (q *Queries) CountContentReleaseRows(ctx context.Context, releaseVersion int64) (CountContentReleaseRowsRow, error) {
	row := q.db.QueryRow(ctx, countContentReleaseRows, releaseVersion)
	var i CountContentReleaseRowsRow
	err := row.Scan(
		&i.BasketMappingCount,
		&i.KeeperDefinitionCount,
		&i.ComponentCount,
		&i.NodeCount,
		&i.StrategyCount,
		&i.RelicCount,
		&i.SynergyCount,
		&i.ModifierCount,
		&i.ObjectiveCount,
		&i.GameRuleSetCount,
	)
	return i, err
}

const getDailyModifierDefinitionVersion = `-- name: GetDailyModifierDefinitionVersion :one
SELECT id, modifier_key, content_version, name, description, rule_key, rule_config, created_at
FROM daily_modifier_definition_versions
WHERE id = $1
`

func (q *Queries) GetDailyModifierDefinitionVersion(ctx context.Context, id pgtype.UUID) (DailyModifierDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getDailyModifierDefinitionVersion, id)
	var i DailyModifierDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.ModifierKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyObjectiveDefinitionVersion = `-- name: GetDailyObjectiveDefinitionVersion :one
SELECT id, objective_key, content_version, name, description, progress_label, reward_label, rule_key, rule_config, created_at
FROM daily_objective_definition_versions
WHERE id = $1
`

func (q *Queries) GetDailyObjectiveDefinitionVersion(ctx context.Context, id pgtype.UUID) (DailyObjectiveDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getDailyObjectiveDefinitionVersion, id)
	var i DailyObjectiveDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.ObjectiveKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.ProgressLabel,
		&i.RewardLabel,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getGameRuleSetVersion = `-- name: GetGameRuleSetVersion :one
SELECT id, rule_set_key, content_version, name, description, rule_key, rule_config, created_at
FROM game_rule_set_versions
WHERE id = $1
`

func (q *Queries) GetGameRuleSetVersion(ctx context.Context, id pgtype.UUID) (GameRuleSetVersion, error) {
	row := q.db.QueryRow(ctx, getGameRuleSetVersion, id)
	var i GameRuleSetVersion
	err := row.Scan(
		&i.ID,
		&i.RuleSetKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getRelicDefinitionVersion = `-- name: GetRelicDefinitionVersion :one
SELECT id, relic_key, content_version, name, description, rule_key, rule_config, created_at
FROM relic_definition_versions
WHERE id = $1
`

func (q *Queries) GetRelicDefinitionVersion(ctx context.Context, id pgtype.UUID) (RelicDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getRelicDefinitionVersion, id)
	var i RelicDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.RelicKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getStrategyDefinitionVersion = `-- name: GetStrategyDefinitionVersion :one
SELECT id, strategy_key, content_version, name, description, upside, downside, rule_key, rule_config, created_at
FROM strategy_definition_versions
WHERE id = $1
`

func (q *Queries) GetStrategyDefinitionVersion(ctx context.Context, id pgtype.UUID) (StrategyDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getStrategyDefinitionVersion, id)
	var i StrategyDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.StrategyKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.Upside,
		&i.Downside,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getSynergyDefinitionVersion = `-- name: GetSynergyDefinitionVersion :one
SELECT id, synergy_key, content_version, name, description, required_count, rule_key, rule_config, created_at
FROM synergy_definition_versions
WHERE id = $1
`

func (q *Queries) GetSynergyDefinitionVersion(ctx context.Context, id pgtype.UUID) (SynergyDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getSynergyDefinitionVersion, id)
	var i SynergyDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.SynergyKey,
		&i.ContentVersion,
		&i.Name,
		&i.Description,
		&i.RequiredCount,
		&i.RuleKey,
		&i.RuleConfig,
		&i.CreatedAt,
	)
	return i, err
}

const insertDailyModifierDefinitionVersion = `-- name: InsertDailyModifierDefinitionVersion :exec
INSERT INTO daily_modifier_definition_versions (
    id, modifier_key, content_version, name, description, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type InsertDailyModifierDefinitionVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	ModifierKey    string      `json:"modifier_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertDailyModifierDefinitionVersion(ctx context.Context, arg InsertDailyModifierDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertDailyModifierDefinitionVersion,
		arg.ID,
		arg.ModifierKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const insertDailyObjectiveDefinitionVersion = `-- name: InsertDailyObjectiveDefinitionVersion :exec
INSERT INTO daily_objective_definition_versions (
    id, objective_key, content_version, name, description, progress_label, reward_label, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9
)
`

type InsertDailyObjectiveDefinitionVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	ObjectiveKey   string      `json:"objective_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	ProgressLabel  *string     `json:"progress_label"`
	RewardLabel    *string     `json:"reward_label"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertDailyObjectiveDefinitionVersion(ctx context.Context, arg InsertDailyObjectiveDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertDailyObjectiveDefinitionVersion,
		arg.ID,
		arg.ObjectiveKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.ProgressLabel,
		arg.RewardLabel,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const insertGameRuleSetVersion = `-- name: InsertGameRuleSetVersion :exec
INSERT INTO game_rule_set_versions (
    id, rule_set_key, content_version, name, description, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type InsertGameRuleSetVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	RuleSetKey     string      `json:"rule_set_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertGameRuleSetVersion(ctx context.Context, arg InsertGameRuleSetVersionParams) error {
	_, err := q.db.Exec(ctx, insertGameRuleSetVersion,
		arg.ID,
		arg.RuleSetKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const insertRelicDefinitionVersion = `-- name: InsertRelicDefinitionVersion :exec
INSERT INTO relic_definition_versions (
    id, relic_key, content_version, name, description, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type InsertRelicDefinitionVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	RelicKey       string      `json:"relic_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertRelicDefinitionVersion(ctx context.Context, arg InsertRelicDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertRelicDefinitionVersion,
		arg.ID,
		arg.RelicKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const insertStrategyDefinitionVersion = `-- name: InsertStrategyDefinitionVersion :exec
INSERT INTO strategy_definition_versions (
    id, strategy_key, content_version, name, description, upside, downside, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9
)
`

type InsertStrategyDefinitionVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	StrategyKey    string      `json:"strategy_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	Upside         string      `json:"upside"`
	Downside       string      `json:"downside"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertStrategyDefinitionVersion(ctx context.Context, arg InsertStrategyDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertStrategyDefinitionVersion,
		arg.ID,
		arg.StrategyKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.Upside,
		arg.Downside,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const insertSynergyDefinitionVersion = `-- name: InsertSynergyDefinitionVersion :exec
INSERT INTO synergy_definition_versions (
    id, synergy_key, content_version, name, description, required_count, rule_key, rule_config
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type InsertSynergyDefinitionVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	SynergyKey     string      `json:"synergy_key"`
	ContentVersion int64       `json:"content_version"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	RequiredCount  int16       `json:"required_count"`
	RuleKey        string      `json:"rule_key"`
	RuleConfig     []byte      `json:"rule_config"`
}

func (q *Queries) InsertSynergyDefinitionVersion(ctx context.Context, arg InsertSynergyDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertSynergyDefinitionVersion,
		arg.ID,
		arg.SynergyKey,
		arg.ContentVersion,
		arg.Name,
		arg.Description,
		arg.RequiredCount,
		arg.RuleKey,
		arg.RuleConfig,
	)
	return err
}

const listCutoverProjectionsForTides = `-- name: ListCutoverProjectionsForTides :many
SELECT pds.daily_tide_id, pds.id AS state_id, v.schema_version, v.projection
FROM player_daily_states AS pds
JOIN player_daily_context_views AS v ON v.player_daily_state_id = pds.id
JOIN daily_tides AS t ON t.id = pds.daily_tide_id
WHERE t.content_version = $1
ORDER BY pds.daily_tide_id, pds.id
`

type ListCutoverProjectionsForTidesRow struct {
	DailyTideID   pgtype.UUID `json:"daily_tide_id"`
	StateID       pgtype.UUID `json:"state_id"`
	SchemaVersion int16       `json:"schema_version"`
	Projection    []byte      `json:"projection"`
}

func (q *Queries) ListCutoverProjectionsForTides(ctx context.Context, sourceVersion int64) ([]ListCutoverProjectionsForTidesRow, error) {
	rows, err := q.db.Query(ctx, listCutoverProjectionsForTides, sourceVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCutoverProjectionsForTidesRow{}
	for rows.Next() {
		var i ListCutoverProjectionsForTidesRow
		if err := rows.Scan(
			&i.DailyTideID,
			&i.StateID,
			&i.SchemaVersion,
			&i.Projection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameRuleSetsForRelease = `-- name: ListGameRuleSetsForRelease :many
SELECT id, rule_set_key, name, description, rule_key, rule_config
FROM game_rule_set_versions
WHERE content_version = $1
ORDER BY rule_set_key
`

type ListGameRuleSetsForReleaseRow struct {
	ID          pgtype.UUID `json:"id"`
	RuleSetKey  string      `json:"rule_set_key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	RuleKey     string      `json:"rule_key"`
	RuleConfig  []byte      `json:"rule_config"`
}

func (q *Queries) ListGameRuleSetsForRelease(ctx context.Context, contentVersion int64) ([]ListGameRuleSetsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listGameRuleSetsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameRuleSetsForReleaseRow{}
	for rows.Next() {
		var i ListGameRuleSetsForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleSetKey,
			&i.Name,
			&i.Description,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyCutoverTides = `-- name: ListLegacyCutoverTides :many
SELECT id, day_key, sequence_number, phase, lock_at, settle_after, content_version,
       modifier_definition_version_id, objective_definition_version_id, game_rule_set_version_id
FROM daily_tides
WHERE content_version = $1
   OR content_version = $2
   OR modifier_definition_version_id IS NOT NULL
   OR objective_definition_version_id IS NOT NULL
   OR game_rule_set_version_id IS NOT NULL
ORDER BY sequence_number
`

type ListLegacyCutoverTidesParams struct {
	SourceVersion int64 `json:"source_version"`
	TargetVersion int64 `json:"target_version"`
}

type ListLegacyCutoverTidesRow struct {
	ID                           pgtype.UUID        `json:"id"`
	DayKey                       pgtype.Date        `json:"day_key"`
	SequenceNumber               int64              `json:"sequence_number"`
	Phase                        string             `json:"phase"`
	LockAt                       pgtype.Timestamptz `json:"lock_at"`
	SettleAfter                  pgtype.Timestamptz `json:"settle_after"`
	ContentVersion               int64              `json:"content_version"`
	ModifierDefinitionVersionID  pgtype.UUID        `json:"modifier_definition_version_id"`
	ObjectiveDefinitionVersionID pgtype.UUID        `json:"objective_definition_version_id"`
	GameRuleSetVersionID         pgtype.UUID        `json:"game_rule_set_version_id"`
}

func (q *Queries) ListLegacyCutoverTides(ctx context.Context, arg ListLegacyCutoverTidesParams) ([]ListLegacyCutoverTidesRow, error) {
	rows, err := q.db.Query(ctx, listLegacyCutoverTides, arg.SourceVersion, arg.TargetVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegacyCutoverTidesRow{}
	for rows.Next() {
		var i ListLegacyCutoverTidesRow
		if err := rows.Scan(
			&i.ID,
			&i.DayKey,
			&i.SequenceNumber,
			&i.Phase,
			&i.LockAt,
			&i.SettleAfter,
			&i.ContentVersion,
			&i.ModifierDefinitionVersionID,
			&i.ObjectiveDefinitionVersionID,
			&i.GameRuleSetVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForRelease = `-- name: ListModifiersForRelease :many
SELECT id, modifier_key, name, description, rule_key, rule_config
FROM daily_modifier_definition_versions
WHERE content_version = $1
ORDER BY modifier_key
`

type ListModifiersForReleaseRow struct {
	ID          pgtype.UUID `json:"id"`
	ModifierKey string      `json:"modifier_key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	RuleKey     string      `json:"rule_key"`
	RuleConfig  []byte      `json:"rule_config"`
}

func (q *Queries) ListModifiersForRelease(ctx context.Context, contentVersion int64) ([]ListModifiersForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listModifiersForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModifiersForReleaseRow{}
	for rows.Next() {
		var i ListModifiersForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ModifierKey,
			&i.Name,
			&i.Description,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectivesForRelease = `-- name: ListObjectivesForRelease :many
SELECT id, objective_key, name, description, progress_label, reward_label, rule_key, rule_config
FROM daily_objective_definition_versions
WHERE content_version = $1
ORDER BY objective_key
`

type ListObjectivesForReleaseRow struct {
	ID            pgtype.UUID `json:"id"`
	ObjectiveKey  string      `json:"objective_key"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	ProgressLabel *string     `json:"progress_label"`
	RewardLabel   *string     `json:"reward_label"`
	RuleKey       string      `json:"rule_key"`
	RuleConfig    []byte      `json:"rule_config"`
}

func (q *Queries) ListObjectivesForRelease(ctx context.Context, contentVersion int64) ([]ListObjectivesForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listObjectivesForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectivesForReleaseRow{}
	for rows.Next() {
		var i ListObjectivesForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ObjectiveKey,
			&i.Name,
			&i.Description,
			&i.ProgressLabel,
			&i.RewardLabel,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelicsForRelease = `-- name: ListRelicsForRelease :many
SELECT id, relic_key, name, description, rule_key, rule_config
FROM relic_definition_versions
WHERE content_version = $1
ORDER BY relic_key
`

type ListRelicsForReleaseRow struct {
	ID          pgtype.UUID `json:"id"`
	RelicKey    string      `json:"relic_key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	RuleKey     string      `json:"rule_key"`
	RuleConfig  []byte      `json:"rule_config"`
}

func (q *Queries) ListRelicsForRelease(ctx context.Context, contentVersion int64) ([]ListRelicsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listRelicsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelicsForReleaseRow{}
	for rows.Next() {
		var i ListRelicsForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.RelicKey,
			&i.Name,
			&i.Description,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategiesForRelease = `-- name: ListStrategiesForRelease :many
SELECT id, strategy_key, name, description, upside, downside, rule_key, rule_config
FROM strategy_definition_versions
WHERE content_version = $1
ORDER BY strategy_key
`

type ListStrategiesForReleaseRow struct {
	ID          pgtype.UUID `json:"id"`
	StrategyKey string      `json:"strategy_key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Upside      string      `json:"upside"`
	Downside    string      `json:"downside"`
	RuleKey     string      `json:"rule_key"`
	RuleConfig  []byte      `json:"rule_config"`
}

func (q *Queries) ListStrategiesForRelease(ctx context.Context, contentVersion int64) ([]ListStrategiesForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listStrategiesForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStrategiesForReleaseRow{}
	for rows.Next() {
		var i ListStrategiesForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.StrategyKey,
			&i.Name,
			&i.Description,
			&i.Upside,
			&i.Downside,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSynergiesForRelease = `-- name: ListSynergiesForRelease :many
SELECT id, synergy_key, name, description, required_count, rule_key, rule_config
FROM synergy_definition_versions
WHERE content_version = $1
ORDER BY synergy_key
`

type ListSynergiesForReleaseRow struct {
	ID            pgtype.UUID `json:"id"`
	SynergyKey    string      `json:"synergy_key"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	RequiredCount int16       `json:"required_count"`
	RuleKey       string      `json:"rule_key"`
	RuleConfig    []byte      `json:"rule_config"`
}

func (q *Queries) ListSynergiesForRelease(ctx context.Context, contentVersion int64) ([]ListSynergiesForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listSynergiesForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSynergiesForReleaseRow{}
	for rows.Next() {
		var i ListSynergiesForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.SynergyKey,
			&i.Name,
			&i.Description,
			&i.RequiredCount,
			&i.RuleKey,
			&i.RuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyTideExactContent = `-- name: UpdateDailyTideExactContent :exec
UPDATE daily_tides
SET content_version = $1,
    modifier_definition_version_id = $2,
    objective_definition_version_id = $3,
    game_rule_set_version_id = $4,
    updated_at = transaction_timestamp()
WHERE id = $5
`

type UpdateDailyTideExactContentParams struct {
	ContentVersion               int64       `json:"content_version"`
	ModifierDefinitionVersionID  pgtype.UUID `json:"modifier_definition_version_id"`
	ObjectiveDefinitionVersionID pgtype.UUID `json:"objective_definition_version_id"`
	GameRuleSetVersionID         pgtype.UUID `json:"game_rule_set_version_id"`
	ID                           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDailyTideExactContent(ctx context.Context, arg UpdateDailyTideExactContentParams) error {
	_, err := q.db.Exec(ctx, updateDailyTideExactContent,
		arg.ContentVersion,
		arg.ModifierDefinitionVersionID,
		arg.ObjectiveDefinitionVersionID,
		arg.GameRuleSetVersionID,
		arg.ID,
	)
	return err
}

const updatePlayerDailyStateSelectedStrategy = `-- name: UpdatePlayerDailyStateSelectedStrategy :exec
UPDATE player_daily_states
SET selected_strategy_definition_version_id = $1,
    updated_at = transaction_timestamp()
WHERE id = $2
`

type UpdatePlayerDailyStateSelectedStrategyParams struct {
	SelectedStrategyDefinitionVersionID pgtype.UUID `json:"selected_strategy_definition_version_id"`
	ID                                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePlayerDailyStateSelectedStrategy(ctx context.Context, arg UpdatePlayerDailyStateSelectedStrategyParams) error {
	_, err := q.db.Exec(ctx, updatePlayerDailyStateSelectedStrategy, arg.SelectedStrategyDefinitionVersionID, arg.ID)
	return err
}

const upsertDailyTideStrategyVersion = `-- name: UpsertDailyTideStrategyVersion :exec
INSERT INTO daily_tide_strategy_versions (
    daily_tide_id, strategy_definition_version_id, content_version
) VALUES (
    $1, $2, $3
)
ON CONFLICT (daily_tide_id, strategy_definition_version_id) DO NOTHING
`

type UpsertDailyTideStrategyVersionParams struct {
	DailyTideID                 pgtype.UUID `json:"daily_tide_id"`
	StrategyDefinitionVersionID pgtype.UUID `json:"strategy_definition_version_id"`
	ContentVersion              int64       `json:"content_version"`
}

func (q *Queries) UpsertDailyTideStrategyVersion(ctx context.Context, arg UpsertDailyTideStrategyVersionParams) error {
	_, err := q.db.Exec(ctx, upsertDailyTideStrategyVersion, arg.DailyTideID, arg.StrategyDefinitionVersionID, arg.ContentVersion)
	return err
}
