// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: daily.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentDailyContextForPlayer = `-- name: GetCurrentDailyContextForPlayer :one
SELECT
    transaction_timestamp()::timestamptz AS server_now,
    p.current_voyage_id,
    v.public_id AS voyage_public_id,
    v.status AS voyage_status,
    v.current_day_number,
    v.fund_health,
    v.max_fund_health,
    v.capital,
    COALESCE(v.score::text, '') AS score,
    v.row_version AS voyage_row_version,
    s.id AS player_daily_state_id,
    s.phase AS player_phase,
    s.version AS player_state_version,
    s.selected_strategy_id,
    s.pending_reward_count,
    t.id AS daily_tide_id,
    t.day_key AS tide_day_key,
    t.sequence_number AS tide_sequence_number,
    t.phase AS tide_phase,
    t.lock_at,
    t.settle_after,
    t.content_version AS tide_content_version,
    cv.schema_version AS projection_schema_version,
    cv.projection,
    cv.validated_at AS projection_validated_at
FROM players AS p
LEFT JOIN voyages AS v
    ON v.id = p.current_voyage_id
   AND v.player_id = p.id
LEFT JOIN player_daily_states AS s
    ON s.player_id = p.id
   AND s.voyage_id = v.id
   AND s.day_number = v.current_day_number
LEFT JOIN daily_tides AS t
    ON t.id = s.daily_tide_id
LEFT JOIN player_daily_context_views AS cv
    ON cv.player_daily_state_id = s.id
WHERE p.id = $1
`

type GetCurrentDailyContextForPlayerRow struct {
	ServerNow               pgtype.Timestamptz `json:"server_now"`
	CurrentVoyageID         pgtype.UUID        `json:"current_voyage_id"`
	VoyagePublicID          *string            `json:"voyage_public_id"`
	VoyageStatus            *string            `json:"voyage_status"`
	CurrentDayNumber        *int16             `json:"current_day_number"`
	FundHealth              *int32             `json:"fund_health"`
	MaxFundHealth           *int32             `json:"max_fund_health"`
	Capital                 *int32             `json:"capital"`
	Score                   interface{}        `json:"score"`
	VoyageRowVersion        *int64             `json:"voyage_row_version"`
	PlayerDailyStateID      pgtype.UUID        `json:"player_daily_state_id"`
	PlayerPhase             *string            `json:"player_phase"`
	PlayerStateVersion      *int64             `json:"player_state_version"`
	SelectedStrategyID      *string            `json:"selected_strategy_id"`
	PendingRewardCount      *int32             `json:"pending_reward_count"`
	DailyTideID             pgtype.UUID        `json:"daily_tide_id"`
	TideDayKey              pgtype.Date        `json:"tide_day_key"`
	TideSequenceNumber      *int64             `json:"tide_sequence_number"`
	TidePhase               *string            `json:"tide_phase"`
	LockAt                  pgtype.Timestamptz `json:"lock_at"`
	SettleAfter             pgtype.Timestamptz `json:"settle_after"`
	TideContentVersion      *int64             `json:"tide_content_version"`
	ProjectionSchemaVersion *int16             `json:"projection_schema_version"`
	Projection              []byte             `json:"projection"`
	ProjectionValidatedAt   pgtype.Timestamptz `json:"projection_validated_at"`
}

func (q *Queries) GetCurrentDailyContextForPlayer(ctx context.Context, playerID pgtype.UUID) (GetCurrentDailyContextForPlayerRow, error) {
	row := q.db.QueryRow(ctx, getCurrentDailyContextForPlayer, playerID)
	var i GetCurrentDailyContextForPlayerRow
	err := row.Scan(
		&i.ServerNow,
		&i.CurrentVoyageID,
		&i.VoyagePublicID,
		&i.VoyageStatus,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.VoyageRowVersion,
		&i.PlayerDailyStateID,
		&i.PlayerPhase,
		&i.PlayerStateVersion,
		&i.SelectedStrategyID,
		&i.PendingRewardCount,
		&i.DailyTideID,
		&i.TideDayKey,
		&i.TideSequenceNumber,
		&i.TidePhase,
		&i.LockAt,
		&i.SettleAfter,
		&i.TideContentVersion,
		&i.ProjectionSchemaVersion,
		&i.Projection,
		&i.ProjectionValidatedAt,
	)
	return i, err
}
