// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keepers.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listKeeperInstancesForPlayer = `-- name: ListKeeperInstancesForPlayer :many
SELECT
    i.public_id AS keeper_public_id,
    d.keeper_key AS definition_key,
    d.name,
    d.current_name,
    d.sector_key,
    d.role_key,
    d.rarity_key,
    i.level
FROM keeper_instances AS i
JOIN keeper_definition_versions AS d
    ON d.id = i.keeper_definition_version_id
WHERE i.player_id = $1
ORDER BY i.acquired_at ASC, i.id ASC
`

type ListKeeperInstancesForPlayerRow struct {
	KeeperPublicID string `json:"keeper_public_id"`
	DefinitionKey  string `json:"definition_key"`
	Name           string `json:"name"`
	CurrentName    string `json:"current_name"`
	SectorKey      string `json:"sector_key"`
	RoleKey        string `json:"role_key"`
	RarityKey      string `json:"rarity_key"`
	Level          int16  `json:"level"`
}

func (q *Queries) ListKeeperInstancesForPlayer(ctx context.Context, playerID pgtype.UUID) ([]ListKeeperInstancesForPlayerRow, error) {
	rows, err := q.db.Query(ctx, listKeeperInstancesForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeeperInstancesForPlayerRow{}
	for rows.Next() {
		var i ListKeeperInstancesForPlayerRow
		if err := rows.Scan(
			&i.KeeperPublicID,
			&i.DefinitionKey,
			&i.Name,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
