// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keepers_catalog.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogReleaseRows = `-- name: CountCatalogReleaseRows :one
SELECT
    (SELECT count(*) FROM keeper_definition_versions AS k WHERE k.content_version = $1)::bigint AS definition_count,
    (SELECT count(*) FROM basket_mapping_versions AS b WHERE b.content_version = $1)::bigint AS mapping_count,
    (SELECT count(*)
     FROM basket_mapping_components AS c
     JOIN basket_mapping_versions AS m ON m.id = c.basket_mapping_version_id
     WHERE m.content_version = $1)::bigint AS component_count,
    (SELECT count(*)
     FROM keeper_definition_upgrade_nodes AS n
     JOIN keeper_definition_versions AS k ON k.id = n.keeper_definition_version_id
     WHERE k.content_version = $1)::bigint AS node_count
`

type CountCatalogReleaseRowsRow struct {
	DefinitionCount int64 `json:"definition_count"`
	MappingCount    int64 `json:"mapping_count"`
	ComponentCount  int64 `json:"component_count"`
	NodeCount       int64 `json:"node_count"`
}

func (q *Queries) CountCatalogReleaseRows(ctx context.Context, releaseVersion int64) (CountCatalogReleaseRowsRow, error) {
	row := q.db.QueryRow(ctx, countCatalogReleaseRows, releaseVersion)
	var i CountCatalogReleaseRowsRow
	err := row.Scan(
		&i.DefinitionCount,
		&i.MappingCount,
		&i.ComponentCount,
		&i.NodeCount,
	)
	return i, err
}

const countKeeperUpgradeNodesForRelease = `-- name: CountKeeperUpgradeNodesForRelease :one
SELECT count(*)::bigint AS node_count
FROM keeper_definition_upgrade_nodes AS n
JOIN keeper_definition_versions AS k ON k.id = n.keeper_definition_version_id
WHERE k.content_version = $1
`

func (q *Queries) CountKeeperUpgradeNodesForRelease(ctx context.Context, releaseVersion int64) (int64, error) {
	row := q.db.QueryRow(ctx, countKeeperUpgradeNodesForRelease, releaseVersion)
	var node_count int64
	err := row.Scan(&node_count)
	return node_count, err
}

const createDraftContentRelease = `-- name: CreateDraftContentRelease :exec
INSERT INTO content_releases (version, status, checksum, checksum_schema_version)
VALUES ($1, 'DRAFT', $2, $3)
`

type CreateDraftContentReleaseParams struct {
	Version               int64  `json:"version"`
	Checksum              []byte `json:"checksum"`
	ChecksumSchemaVersion int16  `json:"checksum_schema_version"`
}

func (q *Queries) CreateDraftContentRelease(ctx context.Context, arg CreateDraftContentReleaseParams) error {
	_, err := q.db.Exec(ctx, createDraftContentRelease, arg.Version, arg.Checksum, arg.ChecksumSchemaVersion)
	return err
}

const getContentRelease = `-- name: GetContentRelease :one
SELECT version, status, checksum, checksum_schema_version, published_at, created_at
FROM content_releases
WHERE version = $1
`

type GetContentReleaseRow struct {
	Version               int64              `json:"version"`
	Status                string             `json:"status"`
	Checksum              []byte             `json:"checksum"`
	ChecksumSchemaVersion int16              `json:"checksum_schema_version"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetContentRelease(ctx context.Context, version int64) (GetContentReleaseRow, error) {
	row := q.db.QueryRow(ctx, getContentRelease, version)
	var i GetContentReleaseRow
	err := row.Scan(
		&i.Version,
		&i.Status,
		&i.Checksum,
		&i.ChecksumSchemaVersion,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMarketAssetByKey = `-- name: GetMarketAssetByKey :one
SELECT id, asset_key, symbol, created_at
FROM market_assets
WHERE asset_key = $1
`

func (q *Queries) GetMarketAssetByKey(ctx context.Context, assetKey string) (MarketAsset, error) {
	row := q.db.QueryRow(ctx, getMarketAssetByKey, assetKey)
	var i MarketAsset
	err := row.Scan(
		&i.ID,
		&i.AssetKey,
		&i.Symbol,
		&i.CreatedAt,
	)
	return i, err
}

const insertBasketMappingComponent = `-- name: InsertBasketMappingComponent :exec
INSERT INTO basket_mapping_components (basket_mapping_version_id, market_asset_id, weight)
VALUES ($1, $2, $3)
`

type InsertBasketMappingComponentParams struct {
	BasketMappingVersionID pgtype.UUID    `json:"basket_mapping_version_id"`
	MarketAssetID          pgtype.UUID    `json:"market_asset_id"`
	Weight                 pgtype.Numeric `json:"weight"`
}

func (q *Queries) InsertBasketMappingComponent(ctx context.Context, arg InsertBasketMappingComponentParams) error {
	_, err := q.db.Exec(ctx, insertBasketMappingComponent, arg.BasketMappingVersionID, arg.MarketAssetID, arg.Weight)
	return err
}

const insertBasketMappingVersion = `-- name: InsertBasketMappingVersion :exec
INSERT INTO basket_mapping_versions (
    id, mapping_key, content_version, sector_definition_version_id,
    minimum_covered_weight_units, expected_turbulence_policy_id,
    normalization_cap_units, benchmark_eligible
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8
)
`

type InsertBasketMappingVersionParams struct {
	ID                         pgtype.UUID `json:"id"`
	MappingKey                 string      `json:"mapping_key"`
	ContentVersion             int64       `json:"content_version"`
	SectorDefinitionVersionID  pgtype.UUID `json:"sector_definition_version_id"`
	MinimumCoveredWeightUnits  *int64      `json:"minimum_covered_weight_units"`
	ExpectedTurbulencePolicyID pgtype.UUID `json:"expected_turbulence_policy_id"`
	NormalizationCapUnits      *int64      `json:"normalization_cap_units"`
	BenchmarkEligible          *bool       `json:"benchmark_eligible"`
}

func (q *Queries) InsertBasketMappingVersion(ctx context.Context, arg InsertBasketMappingVersionParams) error {
	_, err := q.db.Exec(ctx, insertBasketMappingVersion,
		arg.ID,
		arg.MappingKey,
		arg.ContentVersion,
		arg.SectorDefinitionVersionID,
		arg.MinimumCoveredWeightUnits,
		arg.ExpectedTurbulencePolicyID,
		arg.NormalizationCapUnits,
		arg.BenchmarkEligible,
	)
	return err
}

const insertExpectedTurbulencePolicy = `-- name: InsertExpectedTurbulencePolicy :exec
INSERT INTO expected_turbulence_policies (
    id, policy_key, content_version, policy_type, static_value_units, floor_units, rounding_mode
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
`

type InsertExpectedTurbulencePolicyParams struct {
	ID               pgtype.UUID `json:"id"`
	PolicyKey        string      `json:"policy_key"`
	ContentVersion   int64       `json:"content_version"`
	PolicyType       string      `json:"policy_type"`
	StaticValueUnits *int64      `json:"static_value_units"`
	FloorUnits       int64       `json:"floor_units"`
	RoundingMode     string      `json:"rounding_mode"`
}

func (q *Queries) InsertExpectedTurbulencePolicy(ctx context.Context, arg InsertExpectedTurbulencePolicyParams) error {
	_, err := q.db.Exec(ctx, insertExpectedTurbulencePolicy,
		arg.ID,
		arg.PolicyKey,
		arg.ContentVersion,
		arg.PolicyType,
		arg.StaticValueUnits,
		arg.FloorUnits,
		arg.RoundingMode,
	)
	return err
}

const insertKeeperDefinitionUpgradeNode = `-- name: InsertKeeperDefinitionUpgradeNode :exec
INSERT INTO keeper_definition_upgrade_nodes (keeper_definition_version_id, node_key, depth, is_root)
VALUES ($1, $2, $3, $4)
`

type InsertKeeperDefinitionUpgradeNodeParams struct {
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	NodeKey                   string      `json:"node_key"`
	Depth                     int16       `json:"depth"`
	IsRoot                    bool        `json:"is_root"`
}

func (q *Queries) InsertKeeperDefinitionUpgradeNode(ctx context.Context, arg InsertKeeperDefinitionUpgradeNodeParams) error {
	_, err := q.db.Exec(ctx, insertKeeperDefinitionUpgradeNode,
		arg.KeeperDefinitionVersionID,
		arg.NodeKey,
		arg.Depth,
		arg.IsRoot,
	)
	return err
}

const insertKeeperDefinitionVersion = `-- name: InsertKeeperDefinitionVersion :exec
INSERT INTO keeper_definition_versions (
    id,
    keeper_key,
    content_version,
    name,
    current_key,
    current_name,
    sector_key,
    role_key,
    rarity_key,
    base_risk_key,
    expected_turbulence_bps,
    passive_rule_key,
    passive_rule_config,
    upgrade_tree,
    basket_mapping_version_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
`

type InsertKeeperDefinitionVersionParams struct {
	ID                     pgtype.UUID `json:"id"`
	KeeperKey              string      `json:"keeper_key"`
	ContentVersion         int64       `json:"content_version"`
	Name                   string      `json:"name"`
	CurrentKey             string      `json:"current_key"`
	CurrentName            string      `json:"current_name"`
	SectorKey              string      `json:"sector_key"`
	RoleKey                string      `json:"role_key"`
	RarityKey              string      `json:"rarity_key"`
	BaseRiskKey            string      `json:"base_risk_key"`
	ExpectedTurbulenceBps  *int32      `json:"expected_turbulence_bps"`
	PassiveRuleKey         string      `json:"passive_rule_key"`
	PassiveRuleConfig      []byte      `json:"passive_rule_config"`
	UpgradeTree            []byte      `json:"upgrade_tree"`
	BasketMappingVersionID pgtype.UUID `json:"basket_mapping_version_id"`
}

func (q *Queries) InsertKeeperDefinitionVersion(ctx context.Context, arg InsertKeeperDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertKeeperDefinitionVersion,
		arg.ID,
		arg.KeeperKey,
		arg.ContentVersion,
		arg.Name,
		arg.CurrentKey,
		arg.CurrentName,
		arg.SectorKey,
		arg.RoleKey,
		arg.RarityKey,
		arg.BaseRiskKey,
		arg.ExpectedTurbulenceBps,
		arg.PassiveRuleKey,
		arg.PassiveRuleConfig,
		arg.UpgradeTree,
		arg.BasketMappingVersionID,
	)
	return err
}

const insertMarketAsset = `-- name: InsertMarketAsset :exec
INSERT INTO market_assets (id, asset_key, symbol)
VALUES ($1, $2, $3)
`

type InsertMarketAssetParams struct {
	ID       pgtype.UUID `json:"id"`
	AssetKey string      `json:"asset_key"`
	Symbol   string      `json:"symbol"`
}

func (q *Queries) InsertMarketAsset(ctx context.Context, arg InsertMarketAssetParams) error {
	_, err := q.db.Exec(ctx, insertMarketAsset, arg.ID, arg.AssetKey, arg.Symbol)
	return err
}

const insertSectorDefinitionVersion = `-- name: InsertSectorDefinitionVersion :exec
INSERT INTO sector_definition_versions (
    id, sector_key, content_version, benchmark_method, minimum_eligible_baskets,
    relative_scale_units, relative_blend_weight_units, rank_blend_weight_units, score_cap_units
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertSectorDefinitionVersionParams struct {
	ID                       pgtype.UUID `json:"id"`
	SectorKey                string      `json:"sector_key"`
	ContentVersion           int64       `json:"content_version"`
	BenchmarkMethod          string      `json:"benchmark_method"`
	MinimumEligibleBaskets   int32       `json:"minimum_eligible_baskets"`
	RelativeScaleUnits       int64       `json:"relative_scale_units"`
	RelativeBlendWeightUnits int64       `json:"relative_blend_weight_units"`
	RankBlendWeightUnits     int64       `json:"rank_blend_weight_units"`
	ScoreCapUnits            int64       `json:"score_cap_units"`
}

func (q *Queries) InsertSectorDefinitionVersion(ctx context.Context, arg InsertSectorDefinitionVersionParams) error {
	_, err := q.db.Exec(ctx, insertSectorDefinitionVersion,
		arg.ID,
		arg.SectorKey,
		arg.ContentVersion,
		arg.BenchmarkMethod,
		arg.MinimumEligibleBaskets,
		arg.RelativeScaleUnits,
		arg.RelativeBlendWeightUnits,
		arg.RankBlendWeightUnits,
		arg.ScoreCapUnits,
	)
	return err
}

const listBasketComponentsForRelease = `-- name: ListBasketComponentsForRelease :many
SELECT c.basket_mapping_version_id, m.mapping_key, a.asset_key, c.weight
FROM basket_mapping_components AS c
JOIN basket_mapping_versions AS m ON m.id = c.basket_mapping_version_id
JOIN market_assets AS a ON a.id = c.market_asset_id
WHERE m.content_version = $1
ORDER BY m.mapping_key, a.asset_key
`

type ListBasketComponentsForReleaseRow struct {
	BasketMappingVersionID pgtype.UUID    `json:"basket_mapping_version_id"`
	MappingKey             string         `json:"mapping_key"`
	AssetKey               string         `json:"asset_key"`
	Weight                 pgtype.Numeric `json:"weight"`
}

func (q *Queries) ListBasketComponentsForRelease(ctx context.Context, contentVersion int64) ([]ListBasketComponentsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listBasketComponentsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBasketComponentsForReleaseRow{}
	for rows.Next() {
		var i ListBasketComponentsForReleaseRow
		if err := rows.Scan(
			&i.BasketMappingVersionID,
			&i.MappingKey,
			&i.AssetKey,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBasketMappingsForRelease = `-- name: ListBasketMappingsForRelease :many
SELECT m.id, m.mapping_key,
       COALESCE(s.sector_key, '') AS sector_key,
       m.minimum_covered_weight_units,
       COALESCE(t.policy_key, '') AS turbulence_policy_key,
       m.normalization_cap_units,
       m.benchmark_eligible
FROM basket_mapping_versions AS m
LEFT JOIN sector_definition_versions AS s ON s.id = m.sector_definition_version_id
LEFT JOIN expected_turbulence_policies AS t ON t.id = m.expected_turbulence_policy_id
WHERE m.content_version = $1
ORDER BY m.mapping_key
`

type ListBasketMappingsForReleaseRow struct {
	ID                        pgtype.UUID `json:"id"`
	MappingKey                string      `json:"mapping_key"`
	SectorKey                 string      `json:"sector_key"`
	MinimumCoveredWeightUnits *int64      `json:"minimum_covered_weight_units"`
	TurbulencePolicyKey       string      `json:"turbulence_policy_key"`
	NormalizationCapUnits     *int64      `json:"normalization_cap_units"`
	BenchmarkEligible         *bool       `json:"benchmark_eligible"`
}

func (q *Queries) ListBasketMappingsForRelease(ctx context.Context, contentVersion int64) ([]ListBasketMappingsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listBasketMappingsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBasketMappingsForReleaseRow{}
	for rows.Next() {
		var i ListBasketMappingsForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.MappingKey,
			&i.SectorKey,
			&i.MinimumCoveredWeightUnits,
			&i.TurbulencePolicyKey,
			&i.NormalizationCapUnits,
			&i.BenchmarkEligible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeeperDefinitionsForRelease = `-- name: ListKeeperDefinitionsForRelease :many
SELECT k.id, k.keeper_key, k.name, k.current_key, k.current_name,
       k.sector_key, k.role_key, k.rarity_key, k.base_risk_key,
       k.expected_turbulence_bps, k.passive_rule_key, k.passive_rule_config, k.upgrade_tree,
       m.mapping_key AS basket_mapping_key
FROM keeper_definition_versions AS k
JOIN basket_mapping_versions AS m ON m.id = k.basket_mapping_version_id
WHERE k.content_version = $1
ORDER BY k.keeper_key
`

type ListKeeperDefinitionsForReleaseRow struct {
	ID                    pgtype.UUID `json:"id"`
	KeeperKey             string      `json:"keeper_key"`
	Name                  string      `json:"name"`
	CurrentKey            string      `json:"current_key"`
	CurrentName           string      `json:"current_name"`
	SectorKey             string      `json:"sector_key"`
	RoleKey               string      `json:"role_key"`
	RarityKey             string      `json:"rarity_key"`
	BaseRiskKey           string      `json:"base_risk_key"`
	ExpectedTurbulenceBps *int32      `json:"expected_turbulence_bps"`
	PassiveRuleKey        string      `json:"passive_rule_key"`
	PassiveRuleConfig     []byte      `json:"passive_rule_config"`
	UpgradeTree           []byte      `json:"upgrade_tree"`
	BasketMappingKey      string      `json:"basket_mapping_key"`
}

func (q *Queries) ListKeeperDefinitionsForRelease(ctx context.Context, contentVersion int64) ([]ListKeeperDefinitionsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listKeeperDefinitionsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeeperDefinitionsForReleaseRow{}
	for rows.Next() {
		var i ListKeeperDefinitionsForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.KeeperKey,
			&i.Name,
			&i.CurrentKey,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
			&i.BaseRiskKey,
			&i.ExpectedTurbulenceBps,
			&i.PassiveRuleKey,
			&i.PassiveRuleConfig,
			&i.UpgradeTree,
			&i.BasketMappingKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketAssets = `-- name: ListMarketAssets :many
SELECT id, asset_key, symbol
FROM market_assets
ORDER BY asset_key
`

type ListMarketAssetsRow struct {
	ID       pgtype.UUID `json:"id"`
	AssetKey string      `json:"asset_key"`
	Symbol   string      `json:"symbol"`
}

func (q *Queries) ListMarketAssets(ctx context.Context) ([]ListMarketAssetsRow, error) {
	rows, err := q.db.Query(ctx, listMarketAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMarketAssetsRow{}
	for rows.Next() {
		var i ListMarketAssetsRow
		if err := rows.Scan(&i.ID, &i.AssetKey, &i.Symbol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectorDefinitionsForRelease = `-- name: ListSectorDefinitionsForRelease :many
SELECT id, sector_key, benchmark_method, minimum_eligible_baskets,
       relative_scale_units, relative_blend_weight_units, rank_blend_weight_units, score_cap_units
FROM sector_definition_versions
WHERE content_version = $1
ORDER BY sector_key
`

type ListSectorDefinitionsForReleaseRow struct {
	ID                       pgtype.UUID `json:"id"`
	SectorKey                string      `json:"sector_key"`
	BenchmarkMethod          string      `json:"benchmark_method"`
	MinimumEligibleBaskets   int32       `json:"minimum_eligible_baskets"`
	RelativeScaleUnits       int64       `json:"relative_scale_units"`
	RelativeBlendWeightUnits int64       `json:"relative_blend_weight_units"`
	RankBlendWeightUnits     int64       `json:"rank_blend_weight_units"`
	ScoreCapUnits            int64       `json:"score_cap_units"`
}

func (q *Queries) ListSectorDefinitionsForRelease(ctx context.Context, contentVersion int64) ([]ListSectorDefinitionsForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listSectorDefinitionsForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSectorDefinitionsForReleaseRow{}
	for rows.Next() {
		var i ListSectorDefinitionsForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.SectorKey,
			&i.BenchmarkMethod,
			&i.MinimumEligibleBaskets,
			&i.RelativeScaleUnits,
			&i.RelativeBlendWeightUnits,
			&i.RankBlendWeightUnits,
			&i.ScoreCapUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurbulencePoliciesForRelease = `-- name: ListTurbulencePoliciesForRelease :many
SELECT id, policy_key, policy_type, static_value_units, floor_units, rounding_mode
FROM expected_turbulence_policies
WHERE content_version = $1
ORDER BY policy_key
`

type ListTurbulencePoliciesForReleaseRow struct {
	ID               pgtype.UUID `json:"id"`
	PolicyKey        string      `json:"policy_key"`
	PolicyType       string      `json:"policy_type"`
	StaticValueUnits *int64      `json:"static_value_units"`
	FloorUnits       int64       `json:"floor_units"`
	RoundingMode     string      `json:"rounding_mode"`
}

func (q *Queries) ListTurbulencePoliciesForRelease(ctx context.Context, contentVersion int64) ([]ListTurbulencePoliciesForReleaseRow, error) {
	rows, err := q.db.Query(ctx, listTurbulencePoliciesForRelease, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTurbulencePoliciesForReleaseRow{}
	for rows.Next() {
		var i ListTurbulencePoliciesForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyKey,
			&i.PolicyType,
			&i.StaticValueUnits,
			&i.FloorUnits,
			&i.RoundingMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishContentRelease = `-- name: PublishContentRelease :exec
UPDATE content_releases
SET status = 'PUBLISHED', published_at = transaction_timestamp()
WHERE version = $1
  AND status = 'DRAFT'
`

func (q *Queries) PublishContentRelease(ctx context.Context, version int64) error {
	_, err := q.db.Exec(ctx, publishContentRelease, version)
	return err
}
