// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keepers.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPlayerKeeperUnlocks = `-- name: ListPlayerKeeperUnlocks :many
SELECT
    u.keeper_key,
    d.content_version AS definition_version,
    u.unlock_source,
    u.unlocked_at,
    d.name,
    d.current_name,
    d.sector_key,
    d.role_key,
    d.rarity_key
FROM player_keeper_unlocks AS u
JOIN keeper_definition_versions AS d
    ON d.id = u.unlocked_definition_version_id
WHERE u.player_id = $1
ORDER BY u.unlocked_at ASC, u.keeper_key ASC
`

type ListPlayerKeeperUnlocksRow struct {
	KeeperKey         string             `json:"keeper_key"`
	DefinitionVersion int64              `json:"definition_version"`
	UnlockSource      string             `json:"unlock_source"`
	UnlockedAt        pgtype.Timestamptz `json:"unlocked_at"`
	Name              string             `json:"name"`
	CurrentName       string             `json:"current_name"`
	SectorKey         string             `json:"sector_key"`
	RoleKey           string             `json:"role_key"`
	RarityKey         string             `json:"rarity_key"`
}

func (q *Queries) ListPlayerKeeperUnlocks(ctx context.Context, playerID pgtype.UUID) ([]ListPlayerKeeperUnlocksRow, error) {
	rows, err := q.db.Query(ctx, listPlayerKeeperUnlocks, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerKeeperUnlocksRow{}
	for rows.Next() {
		var i ListPlayerKeeperUnlocksRow
		if err := rows.Scan(
			&i.KeeperKey,
			&i.DefinitionVersion,
			&i.UnlockSource,
			&i.UnlockedAt,
			&i.Name,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
