// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
}

type BasketMappingComponent struct {
	BasketMappingVersionID pgtype.UUID        `json:"basket_mapping_version_id"`
	MarketAssetID          pgtype.UUID        `json:"market_asset_id"`
	Weight                 pgtype.Numeric     `json:"weight"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type BasketMappingVersion struct {
	ID                         pgtype.UUID        `json:"id"`
	MappingKey                 string             `json:"mapping_key"`
	ContentVersion             int64              `json:"content_version"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	SectorDefinitionVersionID  pgtype.UUID        `json:"sector_definition_version_id"`
	MinimumCoveredWeightUnits  *int64             `json:"minimum_covered_weight_units"`
	ExpectedTurbulencePolicyID pgtype.UUID        `json:"expected_turbulence_policy_id"`
	NormalizationCapUnits      *int64             `json:"normalization_cap_units"`
	BenchmarkEligible          *bool              `json:"benchmark_eligible"`
}

type BasketMetric struct {
	ID                         pgtype.UUID        `json:"id"`
	DailyTideID                pgtype.UUID        `json:"daily_tide_id"`
	BasketMappingVersionID     pgtype.UUID        `json:"basket_mapping_version_id"`
	CalculationWindowID        pgtype.UUID        `json:"calculation_window_id"`
	Status                     string             `json:"status"`
	CoveredWeightUnits         int64              `json:"covered_weight_units"`
	RawReturnUnits             *int64             `json:"raw_return_units"`
	ExpectedTurbulenceUnits    *int64             `json:"expected_turbulence_units"`
	NormalizedPerformanceUnits *int64             `json:"normalized_performance_units"`
	InputChecksum              []byte             `json:"input_checksum"`
	CalculatedAt               pgtype.Timestamptz `json:"calculated_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type BasketMetricComponent struct {
	ID                   pgtype.UUID        `json:"id"`
	BasketMetricID       pgtype.UUID        `json:"basket_metric_id"`
	MarketAssetID        pgtype.UUID        `json:"market_asset_id"`
	Status               string             `json:"status"`
	TargetWeightUnits    int64              `json:"target_weight_units"`
	EffectiveWeightUnits *int64             `json:"effective_weight_units"`
	OpenObservationID    pgtype.UUID        `json:"open_observation_id"`
	CloseObservationID   pgtype.UUID        `json:"close_observation_id"`
	ComponentReturnUnits *int64             `json:"component_return_units"`
	ContributionUnits    *int64             `json:"contribution_units"`
	QualityFlags         []byte             `json:"quality_flags"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ContentRelease struct {
	Version               int64              `json:"version"`
	Status                string             `json:"status"`
	Checksum              []byte             `json:"checksum"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ChecksumSchemaVersion int16              `json:"checksum_schema_version"`
}

type DailyModifierDefinitionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	ModifierKey    string             `json:"modifier_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DailyObjectiveDefinitionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	ObjectiveKey   string             `json:"objective_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	ProgressLabel  *string            `json:"progress_label"`
	RewardLabel    *string            `json:"reward_label"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DailyTide struct {
	ID                           pgtype.UUID        `json:"id"`
	DayKey                       pgtype.Date        `json:"day_key"`
	SequenceNumber               int64              `json:"sequence_number"`
	Phase                        string             `json:"phase"`
	LockAt                       pgtype.Timestamptz `json:"lock_at"`
	SettleAfter                  pgtype.Timestamptz `json:"settle_after"`
	ContentVersion               int64              `json:"content_version"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	ModifierDefinitionVersionID  pgtype.UUID        `json:"modifier_definition_version_id"`
	ObjectiveDefinitionVersionID pgtype.UUID        `json:"objective_definition_version_id"`
	GameRuleSetVersionID         pgtype.UUID        `json:"game_rule_set_version_id"`
}

type DailyTideStrategyVersion struct {
	DailyTideID                 pgtype.UUID        `json:"daily_tide_id"`
	StrategyDefinitionVersionID pgtype.UUID        `json:"strategy_definition_version_id"`
	ContentVersion              int64              `json:"content_version"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type ExpectedTurbulencePolicy struct {
	ID               pgtype.UUID        `json:"id"`
	PolicyKey        string             `json:"policy_key"`
	ContentVersion   int64              `json:"content_version"`
	PolicyType       string             `json:"policy_type"`
	StaticValueUnits *int64             `json:"static_value_units"`
	FloorUnits       int64              `json:"floor_units"`
	RoundingMode     string             `json:"rounding_mode"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GameRuleSetVersion struct {
	ID             pgtype.UUID        `json:"id"`
	RuleSetKey     string             `json:"rule_set_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	PlayerID       pgtype.UUID        `json:"player_id"`
	Scope          string             `json:"scope"`
	Key            string             `json:"key"`
	State          string             `json:"state"`
	RequestHash    []byte             `json:"request_hash"`
	ResultVoyageID pgtype.UUID        `json:"result_voyage_id"`
	ResponseStatus *int16             `json:"response_status"`
	ResponseJson   []byte             `json:"response_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type KeeperDefinitionUpgradeNode struct {
	KeeperDefinitionVersionID pgtype.UUID        `json:"keeper_definition_version_id"`
	NodeKey                   string             `json:"node_key"`
	Depth                     int16              `json:"depth"`
	IsRoot                    bool               `json:"is_root"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type KeeperDefinitionVersion struct {
	ID                     pgtype.UUID        `json:"id"`
	KeeperKey              string             `json:"keeper_key"`
	ContentVersion         int64              `json:"content_version"`
	Name                   string             `json:"name"`
	CurrentKey             string             `json:"current_key"`
	CurrentName            string             `json:"current_name"`
	SectorKey              string             `json:"sector_key"`
	RoleKey                string             `json:"role_key"`
	RarityKey              string             `json:"rarity_key"`
	BaseRiskKey            string             `json:"base_risk_key"`
	ExpectedTurbulenceBps  *int32             `json:"expected_turbulence_bps"`
	PassiveRuleKey         string             `json:"passive_rule_key"`
	PassiveRuleConfig      []byte             `json:"passive_rule_config"`
	UpgradeTree            []byte             `json:"upgrade_tree"`
	BasketMappingVersionID pgtype.UUID        `json:"basket_mapping_version_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type KeeperInstance struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	KeeperDefinitionVersionID pgtype.UUID        `json:"keeper_definition_version_id"`
	AcquiredAt                pgtype.Timestamptz `json:"acquired_at"`
	VoyageID                  pgtype.UUID        `json:"voyage_id"`
	UpgradeNodeKey            string             `json:"upgrade_node_key"`
	AcquiredDay               int16              `json:"acquired_day"`
	AcquiredSource            string             `json:"acquired_source"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type KeeperSectorResult struct {
	ID                         pgtype.UUID        `json:"id"`
	DailyTideID                pgtype.UUID        `json:"daily_tide_id"`
	KeeperDefinitionVersionID  pgtype.UUID        `json:"keeper_definition_version_id"`
	BasketMetricID             pgtype.UUID        `json:"basket_metric_id"`
	SectorBenchmarkID          pgtype.UUID        `json:"sector_benchmark_id"`
	SectorRelativeUnits        int64              `json:"sector_relative_units"`
	SectorPercentileUnits      int64              `json:"sector_percentile_units"`
	RelativeComponentUnits     int64              `json:"relative_component_units"`
	RankComponentUnits         int64              `json:"rank_component_units"`
	SectorScoreNormalizedUnits int64              `json:"sector_score_normalized_units"`
	SectorScorePoints          int64              `json:"sector_score_points"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type MarketAsset struct {
	ID        pgtype.UUID        `json:"id"`
	AssetKey  string             `json:"asset_key"`
	Symbol    string             `json:"symbol"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MarketCalculationWindow struct {
	ID                          pgtype.UUID        `json:"id"`
	DailyTideID                 pgtype.UUID        `json:"daily_tide_id"`
	ProviderKey                 string             `json:"provider_key"`
	DataWindowStart             pgtype.Timestamptz `json:"data_window_start"`
	DataWindowEnd               pgtype.Timestamptz `json:"data_window_end"`
	RequiredGranularitySeconds  int32              `json:"required_granularity_seconds"`
	ObservationToleranceSeconds int32              `json:"observation_tolerance_seconds"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type MarketPriceObservation struct {
	ID                  pgtype.UUID        `json:"id"`
	CalculationWindowID pgtype.UUID        `json:"calculation_window_id"`
	MarketAssetID       pgtype.UUID        `json:"market_asset_id"`
	ObservedAt          pgtype.Timestamptz `json:"observed_at"`
	RawPrice            string             `json:"raw_price"`
	Price               pgtype.Numeric     `json:"price"`
	QualityStatus       string             `json:"quality_status"`
	QualityFlags        []byte             `json:"quality_flags"`
	RawResponseHash     []byte             `json:"raw_response_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Player struct {
	ID                  pgtype.UUID        `json:"id"`
	AccountID           pgtype.UUID        `json:"account_id"`
	PublicID            string             `json:"public_id"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	Locale              string             `json:"locale"`
	Timezone            string             `json:"timezone"`
	CurrentVoyageID     pgtype.UUID        `json:"current_voyage_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type PlayerDailyContextView struct {
	PlayerDailyStateID pgtype.UUID        `json:"player_daily_state_id"`
	SchemaVersion      int16              `json:"schema_version"`
	Projection         []byte             `json:"projection"`
	ValidatedAt        pgtype.Timestamptz `json:"validated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PlayerDailyState struct {
	ID                                  pgtype.UUID        `json:"id"`
	PlayerID                            pgtype.UUID        `json:"player_id"`
	VoyageID                            pgtype.UUID        `json:"voyage_id"`
	DailyTideID                         pgtype.UUID        `json:"daily_tide_id"`
	DayNumber                           int16              `json:"day_number"`
	Phase                               string             `json:"phase"`
	Version                             int64              `json:"version"`
	SelectedStrategyID                  *string            `json:"selected_strategy_id"`
	PendingRewardCount                  int32              `json:"pending_reward_count"`
	CreatedAt                           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                           pgtype.Timestamptz `json:"updated_at"`
	SelectedStrategyDefinitionVersionID pgtype.UUID        `json:"selected_strategy_definition_version_id"`
}

type PlayerKeeperUnlock struct {
	PlayerID                    pgtype.UUID        `json:"player_id"`
	KeeperKey                   string             `json:"keeper_key"`
	UnlockedDefinitionVersionID pgtype.UUID        `json:"unlocked_definition_version_id"`
	UnlockSource                string             `json:"unlock_source"`
	UnlockedAt                  pgtype.Timestamptz `json:"unlocked_at"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type RelicDefinitionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	RelicKey       string             `json:"relic_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Sector struct {
	SectorKey  string             `json:"sector_key"`
	NameKey    string             `json:"name_key"`
	SummaryKey string             `json:"summary_key"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SectorBenchmark struct {
	ID                        pgtype.UUID        `json:"id"`
	DailyTideID               pgtype.UUID        `json:"daily_tide_id"`
	SectorDefinitionVersionID pgtype.UUID        `json:"sector_definition_version_id"`
	Status                    string             `json:"status"`
	CalculationMethod         string             `json:"calculation_method"`
	EligibleBasketCount       int32              `json:"eligible_basket_count"`
	BenchmarkUnits            *int64             `json:"benchmark_units"`
	MinimumRequiredBaskets    int32              `json:"minimum_required_baskets"`
	InputChecksum             []byte             `json:"input_checksum"`
	CalculatedAt              pgtype.Timestamptz `json:"calculated_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type SectorBenchmarkMember struct {
	ID                         pgtype.UUID        `json:"id"`
	SectorBenchmarkID          pgtype.UUID        `json:"sector_benchmark_id"`
	BasketMetricID             pgtype.UUID        `json:"basket_metric_id"`
	BenchmarkWeightUnits       int64              `json:"benchmark_weight_units"`
	NormalizedPerformanceUnits int64              `json:"normalized_performance_units"`
	ContributionUnits          int64              `json:"contribution_units"`
	RankIndexUnits             int64              `json:"rank_index_units"`
	RankPercentileUnits        int64              `json:"rank_percentile_units"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type SectorDefinitionVersion struct {
	ID                       pgtype.UUID        `json:"id"`
	SectorKey                string             `json:"sector_key"`
	ContentVersion           int64              `json:"content_version"`
	BenchmarkMethod          string             `json:"benchmark_method"`
	MinimumEligibleBaskets   int32              `json:"minimum_eligible_baskets"`
	RelativeScaleUnits       int64              `json:"relative_scale_units"`
	RelativeBlendWeightUnits int64              `json:"relative_blend_weight_units"`
	RankBlendWeightUnits     int64              `json:"rank_blend_weight_units"`
	ScoreCapUnits            int64              `json:"score_cap_units"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                  pgtype.UUID        `json:"id"`
	AccountID           pgtype.UUID        `json:"account_id"`
	PlayerID            pgtype.UUID        `json:"player_id"`
	TokenDigest         []byte             `json:"token_digest"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	RotatedAt           pgtype.Timestamptz `json:"rotated_at"`
	ReplacedBySessionID pgtype.UUID        `json:"replaced_by_session_id"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type StrategyDefinitionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	StrategyKey    string             `json:"strategy_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	Upside         string             `json:"upside"`
	Downside       string             `json:"downside"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SynergyDefinitionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	SynergyKey     string             `json:"synergy_key"`
	ContentVersion int64              `json:"content_version"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	RequiredCount  int16              `json:"required_count"`
	RuleKey        string             `json:"rule_key"`
	RuleConfig     []byte             `json:"rule_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Voyage struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
}

type VoyageDefinitionInitialShopOffer struct {
	VoyageDefinitionVersionID pgtype.UUID `json:"voyage_definition_version_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	Position                  int16       `json:"position"`
	Cost                      int32       `json:"cost"`
}

type VoyageDefinitionStarterKeeper struct {
	VoyageDefinitionVersionID pgtype.UUID `json:"voyage_definition_version_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	Position                  int16       `json:"position"`
}

type VoyageDefinitionVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	DefinitionKey      string             `json:"definition_key"`
	Version            int64              `json:"version"`
	Status             string             `json:"status"`
	DurationDays       int16              `json:"duration_days"`
	StartingHull       int32              `json:"starting_hull"`
	StartingSupplies   int32              `json:"starting_supplies"`
	FleetSlotCount     int16              `json:"fleet_slot_count"`
	InitialPhase       string             `json:"initial_phase"`
	LaunchPresentation []byte             `json:"launch_presentation"`
	Checksum           []byte             `json:"checksum"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type VoyageLedgerEntry struct {
	ID           pgtype.UUID        `json:"id"`
	VoyageID     pgtype.UUID        `json:"voyage_id"`
	EntryType    string             `json:"entry_type"`
	Amount       int32              `json:"amount"`
	BalanceAfter int32              `json:"balance_after"`
	SourceType   string             `json:"source_type"`
	SourceID     string             `json:"source_id"`
	ReasonKey    string             `json:"reason_key"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VoyageLifecycleEvent struct {
	ID              pgtype.UUID        `json:"id"`
	PublicID        string             `json:"public_id"`
	VoyageID        pgtype.UUID        `json:"voyage_id"`
	EventType       string             `json:"event_type"`
	ResultingStatus string             `json:"resulting_status"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
