// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: players.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMeForPlayer = `-- name: GetMeForPlayer :one
SELECT
    p.id AS player_id,
    p.public_id AS player_public_id,
    p.onboarding_completed,
    p.locale,
    p.timezone,
    v.public_id AS current_voyage_public_id
FROM players AS p
LEFT JOIN voyages AS v
    ON v.id = p.current_voyage_id
   AND v.player_id = p.id
WHERE p.id = $1
`

type GetMeForPlayerRow struct {
	PlayerID              pgtype.UUID `json:"player_id"`
	PlayerPublicID        string      `json:"player_public_id"`
	OnboardingCompleted   bool        `json:"onboarding_completed"`
	Locale                string      `json:"locale"`
	Timezone              string      `json:"timezone"`
	CurrentVoyagePublicID *string     `json:"current_voyage_public_id"`
}

func (q *Queries) GetMeForPlayer(ctx context.Context, playerID pgtype.UUID) (GetMeForPlayerRow, error) {
	row := q.db.QueryRow(ctx, getMeForPlayer, playerID)
	var i GetMeForPlayerRow
	err := row.Scan(
		&i.PlayerID,
		&i.PlayerPublicID,
		&i.OnboardingCompleted,
		&i.Locale,
		&i.Timezone,
		&i.CurrentVoyagePublicID,
	)
	return i, err
}
