// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCatalogReleaseRows(ctx context.Context, releaseVersion int64) (CountCatalogReleaseRowsRow, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateDraftContentRelease(ctx context.Context, arg CreateDraftContentReleaseParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	GetAccountForLogin(ctx context.Context, email string) (GetAccountForLoginRow, error)
	GetAuthenticatedSession(ctx context.Context, tokenDigest []byte) (GetAuthenticatedSessionRow, error)
	GetBasketCalculationMapping(ctx context.Context, basketMappingVersionID pgtype.UUID) (GetBasketCalculationMappingRow, error)
	GetBasketMetricByTideAndMapping(ctx context.Context, arg GetBasketMetricByTideAndMappingParams) (BasketMetric, error)
	GetContentRelease(ctx context.Context, version int64) (ContentRelease, error)
	GetCurrentDailyContextForPlayer(ctx context.Context, playerID pgtype.UUID) (GetCurrentDailyContextForPlayerRow, error)
	GetKeeperSectorResultByTideAndDefinition(ctx context.Context, arg GetKeeperSectorResultByTideAndDefinitionParams) (KeeperSectorResult, error)
	GetMarketAssetByKey(ctx context.Context, assetKey string) (MarketAsset, error)
	GetMeForPlayer(ctx context.Context, playerID pgtype.UUID) (GetMeForPlayerRow, error)
	GetSectorBenchmarkByTideAndDefinition(ctx context.Context, arg GetSectorBenchmarkByTideAndDefinitionParams) (SectorBenchmark, error)
	InsertBasketMappingComponent(ctx context.Context, arg InsertBasketMappingComponentParams) error
	InsertBasketMappingVersion(ctx context.Context, arg InsertBasketMappingVersionParams) error
	InsertBasketMetric(ctx context.Context, arg InsertBasketMetricParams) error
	InsertBasketMetricComponent(ctx context.Context, arg InsertBasketMetricComponentParams) error
	InsertExpectedTurbulencePolicy(ctx context.Context, arg InsertExpectedTurbulencePolicyParams) error
	InsertKeeperDefinitionVersion(ctx context.Context, arg InsertKeeperDefinitionVersionParams) error
	InsertKeeperSectorResult(ctx context.Context, arg InsertKeeperSectorResultParams) error
	InsertMarketAsset(ctx context.Context, arg InsertMarketAssetParams) error
	InsertMarketCalculationWindow(ctx context.Context, arg InsertMarketCalculationWindowParams) error
	InsertMarketPriceObservation(ctx context.Context, arg InsertMarketPriceObservationParams) error
	InsertSectorBenchmark(ctx context.Context, arg InsertSectorBenchmarkParams) error
	InsertSectorBenchmarkMember(ctx context.Context, arg InsertSectorBenchmarkMemberParams) error
	InsertSectorDefinitionVersion(ctx context.Context, arg InsertSectorDefinitionVersionParams) error
	ListBasketCalculationMappingComponents(ctx context.Context, basketMappingVersionID pgtype.UUID) ([]BasketMappingComponent, error)
	ListBasketMetricComponents(ctx context.Context, basketMetricID pgtype.UUID) ([]BasketMetricComponent, error)
	ListKeeperInstancesForPlayer(ctx context.Context, playerID pgtype.UUID) ([]ListKeeperInstancesForPlayerRow, error)
	ListMarketPriceObservationsForAsset(ctx context.Context, arg ListMarketPriceObservationsForAssetParams) ([]MarketPriceObservation, error)
	ListReadyBasketMetricsForSectorBenchmark(ctx context.Context, arg ListReadyBasketMetricsForSectorBenchmarkParams) ([]BasketMetric, error)
	ListSectorBenchmarkMembers(ctx context.Context, sectorBenchmarkID pgtype.UUID) ([]SectorBenchmarkMember, error)
	ListTargetBasketCalculationMappingsForContent(ctx context.Context, contentVersion int64) ([]ListTargetBasketCalculationMappingsForContentRow, error)
	ListTargetSectorBenchmarkReadiness(ctx context.Context, arg ListTargetSectorBenchmarkReadinessParams) ([]ListTargetSectorBenchmarkReadinessRow, error)
	PublishContentRelease(ctx context.Context, version int64) error
}

var _ Querier = (*Queries)(nil)
