// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CountCatalogReleaseRows(ctx context.Context, releaseVersion int64) (CountCatalogReleaseRowsRow, error)
	CountContentReleaseRows(ctx context.Context, releaseVersion int64) (CountContentReleaseRowsRow, error)
	CountKeeperUpgradeNodesForRelease(ctx context.Context, releaseVersion int64) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateDraftContentRelease(ctx context.Context, arg CreateDraftContentReleaseParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	GetAccountForLogin(ctx context.Context, email string) (GetAccountForLoginRow, error)
	GetActiveVoyageForPlayer(ctx context.Context, playerID pgtype.UUID) (GetActiveVoyageForPlayerRow, error)
	GetAuthenticatedSession(ctx context.Context, tokenDigest []byte) (GetAuthenticatedSessionRow, error)
	GetBasketCalculationMapping(ctx context.Context, basketMappingVersionID pgtype.UUID) (GetBasketCalculationMappingRow, error)
	GetBasketMetricByTideAndMapping(ctx context.Context, arg GetBasketMetricByTideAndMappingParams) (BasketMetric, error)
	GetContentRelease(ctx context.Context, version int64) (GetContentReleaseRow, error)
	GetCurrentDailyContextForPlayer(ctx context.Context, playerID pgtype.UUID) (GetCurrentDailyContextForPlayerRow, error)
	GetCurrentVoyageForPlayer(ctx context.Context, playerID pgtype.UUID) (GetCurrentVoyageForPlayerRow, error)
	GetDailyModifierDefinitionVersion(ctx context.Context, id pgtype.UUID) (DailyModifierDefinitionVersion, error)
	GetDailyObjectiveDefinitionVersion(ctx context.Context, id pgtype.UUID) (DailyObjectiveDefinitionVersion, error)
	GetGameRuleSetVersion(ctx context.Context, id pgtype.UUID) (GameRuleSetVersion, error)
	GetIdempotencyKeyForUpdate(ctx context.Context, arg GetIdempotencyKeyForUpdateParams) (IdempotencyKey, error)
	GetKeeperSectorResultByTideAndDefinition(ctx context.Context, arg GetKeeperSectorResultByTideAndDefinitionParams) (KeeperSectorResult, error)
	GetMarketAssetByKey(ctx context.Context, assetKey string) (MarketAsset, error)
	GetMeForPlayer(ctx context.Context, playerID pgtype.UUID) (GetMeForPlayerRow, error)
	GetOpenDailyTide(ctx context.Context, dayKey pgtype.Date) (GetOpenDailyTideRow, error)
	GetPublishedVoyageDefinition(ctx context.Context, definitionKey string) (VoyageDefinitionVersion, error)
	GetRelicDefinitionVersion(ctx context.Context, id pgtype.UUID) (RelicDefinitionVersion, error)
	GetSectorBenchmarkByTideAndDefinition(ctx context.Context, arg GetSectorBenchmarkByTideAndDefinitionParams) (SectorBenchmark, error)
	GetStrategyDefinitionVersion(ctx context.Context, id pgtype.UUID) (StrategyDefinitionVersion, error)
	GetSynergyDefinitionVersion(ctx context.Context, id pgtype.UUID) (SynergyDefinitionVersion, error)
	GetVoyageByPublicID(ctx context.Context, publicID string) (GetVoyageByPublicIDRow, error)
	GetVoyageByPublicIDAndPlayerID(ctx context.Context, arg GetVoyageByPublicIDAndPlayerIDParams) (GetVoyageByPublicIDAndPlayerIDRow, error)
	GetVoyageDefinitionByID(ctx context.Context, id pgtype.UUID) (VoyageDefinitionVersion, error)
	GetVoyageDefinitionInitialOffers(ctx context.Context, voyageDefinitionVersionID pgtype.UUID) ([]GetVoyageDefinitionInitialOffersRow, error)
	GetVoyageDefinitionStarterKeepers(ctx context.Context, voyageDefinitionVersionID pgtype.UUID) ([]GetVoyageDefinitionStarterKeepersRow, error)
	InsertBasketMappingComponent(ctx context.Context, arg InsertBasketMappingComponentParams) error
	InsertBasketMappingVersion(ctx context.Context, arg InsertBasketMappingVersionParams) error
	InsertBasketMetric(ctx context.Context, arg InsertBasketMetricParams) error
	InsertBasketMetricComponent(ctx context.Context, arg InsertBasketMetricComponentParams) error
	InsertDailyModifierDefinitionVersion(ctx context.Context, arg InsertDailyModifierDefinitionVersionParams) error
	InsertDailyObjectiveDefinitionVersion(ctx context.Context, arg InsertDailyObjectiveDefinitionVersionParams) error
	InsertExpectedTurbulencePolicy(ctx context.Context, arg InsertExpectedTurbulencePolicyParams) error
	InsertGameRuleSetVersion(ctx context.Context, arg InsertGameRuleSetVersionParams) error
	InsertKeeperDefinitionUpgradeNode(ctx context.Context, arg InsertKeeperDefinitionUpgradeNodeParams) error
	InsertKeeperDefinitionVersion(ctx context.Context, arg InsertKeeperDefinitionVersionParams) error
	InsertKeeperInstance(ctx context.Context, arg InsertKeeperInstanceParams) error
	InsertKeeperSectorResult(ctx context.Context, arg InsertKeeperSectorResultParams) error
	InsertMarketAsset(ctx context.Context, arg InsertMarketAssetParams) error
	InsertMarketCalculationWindow(ctx context.Context, arg InsertMarketCalculationWindowParams) error
	InsertMarketPriceObservation(ctx context.Context, arg InsertMarketPriceObservationParams) error
	InsertPlayerDailyStateWithView(ctx context.Context, arg InsertPlayerDailyStateWithViewParams) error
	InsertRelicDefinitionVersion(ctx context.Context, arg InsertRelicDefinitionVersionParams) error
	InsertSectorBenchmark(ctx context.Context, arg InsertSectorBenchmarkParams) error
	InsertSectorBenchmarkMember(ctx context.Context, arg InsertSectorBenchmarkMemberParams) error
	InsertSectorDefinitionVersion(ctx context.Context, arg InsertSectorDefinitionVersionParams) error
	InsertStrategyDefinitionVersion(ctx context.Context, arg InsertStrategyDefinitionVersionParams) error
	InsertSynergyDefinitionVersion(ctx context.Context, arg InsertSynergyDefinitionVersionParams) error
	InsertVoyage(ctx context.Context, arg InsertVoyageParams) (InsertVoyageRow, error)
	InsertVoyageLedgerEntry(ctx context.Context, arg InsertVoyageLedgerEntryParams) error
	InsertVoyageLifecycleEvent(ctx context.Context, arg InsertVoyageLifecycleEventParams) error
	ListBasketCalculationMappingComponents(ctx context.Context, basketMappingVersionID pgtype.UUID) ([]BasketMappingComponent, error)
	ListBasketComponentsForRelease(ctx context.Context, contentVersion int64) ([]ListBasketComponentsForReleaseRow, error)
	ListBasketMappingsForRelease(ctx context.Context, contentVersion int64) ([]ListBasketMappingsForReleaseRow, error)
	ListBasketMetricComponents(ctx context.Context, basketMetricID pgtype.UUID) ([]BasketMetricComponent, error)
	ListCutoverProjectionsForTides(ctx context.Context, sourceVersion int64) ([]ListCutoverProjectionsForTidesRow, error)
	ListGameRuleSetsForRelease(ctx context.Context, contentVersion int64) ([]ListGameRuleSetsForReleaseRow, error)
	ListKeeperDefinitionsForRelease(ctx context.Context, contentVersion int64) ([]ListKeeperDefinitionsForReleaseRow, error)
	ListLegacyCutoverTides(ctx context.Context, arg ListLegacyCutoverTidesParams) ([]ListLegacyCutoverTidesRow, error)
	ListLifecycleEventsForVoyage(ctx context.Context, voyageID pgtype.UUID) ([]VoyageLifecycleEvent, error)
	ListMarketAssets(ctx context.Context) ([]ListMarketAssetsRow, error)
	ListMarketPriceObservationsForAsset(ctx context.Context, arg ListMarketPriceObservationsForAssetParams) ([]MarketPriceObservation, error)
	ListModifiersForRelease(ctx context.Context, contentVersion int64) ([]ListModifiersForReleaseRow, error)
	ListObjectivesForRelease(ctx context.Context, contentVersion int64) ([]ListObjectivesForReleaseRow, error)
	ListPlayerKeeperUnlocks(ctx context.Context, playerID pgtype.UUID) ([]ListPlayerKeeperUnlocksRow, error)
	ListReadyBasketMetricsForSectorBenchmark(ctx context.Context, arg ListReadyBasketMetricsForSectorBenchmarkParams) ([]BasketMetric, error)
	ListRelicsForRelease(ctx context.Context, contentVersion int64) ([]ListRelicsForReleaseRow, error)
	ListSectorBenchmarkMembers(ctx context.Context, sectorBenchmarkID pgtype.UUID) ([]SectorBenchmarkMember, error)
	ListSectorDefinitionsForRelease(ctx context.Context, contentVersion int64) ([]ListSectorDefinitionsForReleaseRow, error)
	ListStrategiesForRelease(ctx context.Context, contentVersion int64) ([]ListStrategiesForReleaseRow, error)
	ListSynergiesForRelease(ctx context.Context, contentVersion int64) ([]ListSynergiesForReleaseRow, error)
	ListTargetBasketCalculationMappingsForContent(ctx context.Context, contentVersion int64) ([]ListTargetBasketCalculationMappingsForContentRow, error)
	ListTargetSectorBenchmarkReadiness(ctx context.Context, arg ListTargetSectorBenchmarkReadinessParams) ([]ListTargetSectorBenchmarkReadinessRow, error)
	ListTurbulencePoliciesForRelease(ctx context.Context, contentVersion int64) ([]ListTurbulencePoliciesForReleaseRow, error)
	ListVoyageKeepers(ctx context.Context, voyageID pgtype.UUID) ([]ListVoyageKeepersRow, error)
	LockPlayerRow(ctx context.Context, id pgtype.UUID) (Player, error)
	LockVoyageRowForUpdate(ctx context.Context, id pgtype.UUID) (LockVoyageRowForUpdateRow, error)
	PublishContentRelease(ctx context.Context, version int64) error
	UpdateDailyTideExactContent(ctx context.Context, arg UpdateDailyTideExactContentParams) error
	UpdatePlayerCurrentVoyage(ctx context.Context, arg UpdatePlayerCurrentVoyageParams) error
	UpdatePlayerDailyStateSelectedStrategy(ctx context.Context, arg UpdatePlayerDailyStateSelectedStrategyParams) error
	UpdateVoyageStatus(ctx context.Context, arg UpdateVoyageStatusParams) (UpdateVoyageStatusRow, error)
	UpsertDailyTideStrategyVersion(ctx context.Context, arg UpsertDailyTideStrategyVersionParams) error
}

var _ Querier = (*Queries)(nil)
