// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sector_calculation.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBasketCalculationMapping = `-- name: GetBasketCalculationMapping :one
SELECT
    mapping.id AS basket_mapping_version_id,
    mapping.mapping_key,
    mapping.content_version,
    mapping.minimum_covered_weight_units,
    mapping.normalization_cap_units,
    mapping.benchmark_eligible,
    definition.id AS sector_definition_version_id,
    definition.sector_key,
    definition.benchmark_method,
    definition.minimum_eligible_baskets,
    definition.relative_scale_units,
    definition.relative_blend_weight_units,
    definition.rank_blend_weight_units,
    definition.score_cap_units,
    policy.id AS expected_turbulence_policy_id,
    policy.policy_key AS expected_turbulence_policy_key,
    policy.policy_type AS expected_turbulence_policy_type,
    policy.static_value_units AS expected_turbulence_static_value_units,
    policy.floor_units AS expected_turbulence_floor_units,
    policy.rounding_mode AS expected_turbulence_rounding_mode
FROM basket_mapping_versions AS mapping
JOIN sector_definition_versions AS definition
    ON definition.id = mapping.sector_definition_version_id
JOIN expected_turbulence_policies AS policy
    ON policy.id = mapping.expected_turbulence_policy_id
WHERE mapping.id = $1
`

type GetBasketCalculationMappingRow struct {
	BasketMappingVersionID             pgtype.UUID `json:"basket_mapping_version_id"`
	MappingKey                         string      `json:"mapping_key"`
	ContentVersion                     int64       `json:"content_version"`
	MinimumCoveredWeightUnits          *int64      `json:"minimum_covered_weight_units"`
	NormalizationCapUnits              *int64      `json:"normalization_cap_units"`
	BenchmarkEligible                  *bool       `json:"benchmark_eligible"`
	SectorDefinitionVersionID          pgtype.UUID `json:"sector_definition_version_id"`
	SectorKey                          string      `json:"sector_key"`
	BenchmarkMethod                    string      `json:"benchmark_method"`
	MinimumEligibleBaskets             int32       `json:"minimum_eligible_baskets"`
	RelativeScaleUnits                 int64       `json:"relative_scale_units"`
	RelativeBlendWeightUnits           int64       `json:"relative_blend_weight_units"`
	RankBlendWeightUnits               int64       `json:"rank_blend_weight_units"`
	ScoreCapUnits                      int64       `json:"score_cap_units"`
	ExpectedTurbulencePolicyID         pgtype.UUID `json:"expected_turbulence_policy_id"`
	ExpectedTurbulencePolicyKey        string      `json:"expected_turbulence_policy_key"`
	ExpectedTurbulencePolicyType       string      `json:"expected_turbulence_policy_type"`
	ExpectedTurbulenceStaticValueUnits *int64      `json:"expected_turbulence_static_value_units"`
	ExpectedTurbulenceFloorUnits       int64       `json:"expected_turbulence_floor_units"`
	ExpectedTurbulenceRoundingMode     string      `json:"expected_turbulence_rounding_mode"`
}

func (q *Queries) GetBasketCalculationMapping(ctx context.Context, basketMappingVersionID pgtype.UUID) (GetBasketCalculationMappingRow, error) {
	row := q.db.QueryRow(ctx, getBasketCalculationMapping, basketMappingVersionID)
	var i GetBasketCalculationMappingRow
	err := row.Scan(
		&i.BasketMappingVersionID,
		&i.MappingKey,
		&i.ContentVersion,
		&i.MinimumCoveredWeightUnits,
		&i.NormalizationCapUnits,
		&i.BenchmarkEligible,
		&i.SectorDefinitionVersionID,
		&i.SectorKey,
		&i.BenchmarkMethod,
		&i.MinimumEligibleBaskets,
		&i.RelativeScaleUnits,
		&i.RelativeBlendWeightUnits,
		&i.RankBlendWeightUnits,
		&i.ScoreCapUnits,
		&i.ExpectedTurbulencePolicyID,
		&i.ExpectedTurbulencePolicyKey,
		&i.ExpectedTurbulencePolicyType,
		&i.ExpectedTurbulenceStaticValueUnits,
		&i.ExpectedTurbulenceFloorUnits,
		&i.ExpectedTurbulenceRoundingMode,
	)
	return i, err
}

const getBasketMetricByTideAndMapping = `-- name: GetBasketMetricByTideAndMapping :one
SELECT id, daily_tide_id, basket_mapping_version_id, calculation_window_id, status,
       covered_weight_units, raw_return_units, expected_turbulence_units,
       normalized_performance_units, input_checksum, calculated_at, created_at
FROM basket_metrics
WHERE daily_tide_id = $1
  AND basket_mapping_version_id = $2
`

type GetBasketMetricByTideAndMappingParams struct {
	DailyTideID            pgtype.UUID `json:"daily_tide_id"`
	BasketMappingVersionID pgtype.UUID `json:"basket_mapping_version_id"`
}

func (q *Queries) GetBasketMetricByTideAndMapping(ctx context.Context, arg GetBasketMetricByTideAndMappingParams) (BasketMetric, error) {
	row := q.db.QueryRow(ctx, getBasketMetricByTideAndMapping, arg.DailyTideID, arg.BasketMappingVersionID)
	var i BasketMetric
	err := row.Scan(
		&i.ID,
		&i.DailyTideID,
		&i.BasketMappingVersionID,
		&i.CalculationWindowID,
		&i.Status,
		&i.CoveredWeightUnits,
		&i.RawReturnUnits,
		&i.ExpectedTurbulenceUnits,
		&i.NormalizedPerformanceUnits,
		&i.InputChecksum,
		&i.CalculatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKeeperSectorResultByTideAndDefinition = `-- name: GetKeeperSectorResultByTideAndDefinition :one
SELECT id, daily_tide_id, keeper_definition_version_id, basket_metric_id,
       sector_benchmark_id, sector_relative_units, sector_percentile_units,
       relative_component_units, rank_component_units,
       sector_score_normalized_units, sector_score_points, created_at
FROM keeper_sector_results
WHERE daily_tide_id = $1
  AND keeper_definition_version_id = $2
`

type GetKeeperSectorResultByTideAndDefinitionParams struct {
	DailyTideID               pgtype.UUID `json:"daily_tide_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
}

func (q *Queries) GetKeeperSectorResultByTideAndDefinition(ctx context.Context, arg GetKeeperSectorResultByTideAndDefinitionParams) (KeeperSectorResult, error) {
	row := q.db.QueryRow(ctx, getKeeperSectorResultByTideAndDefinition, arg.DailyTideID, arg.KeeperDefinitionVersionID)
	var i KeeperSectorResult
	err := row.Scan(
		&i.ID,
		&i.DailyTideID,
		&i.KeeperDefinitionVersionID,
		&i.BasketMetricID,
		&i.SectorBenchmarkID,
		&i.SectorRelativeUnits,
		&i.SectorPercentileUnits,
		&i.RelativeComponentUnits,
		&i.RankComponentUnits,
		&i.SectorScoreNormalizedUnits,
		&i.SectorScorePoints,
		&i.CreatedAt,
	)
	return i, err
}

const getSectorBenchmarkByTideAndDefinition = `-- name: GetSectorBenchmarkByTideAndDefinition :one
SELECT id, daily_tide_id, sector_definition_version_id, status, calculation_method,
       eligible_basket_count, benchmark_units, minimum_required_baskets,
       input_checksum, calculated_at, created_at
FROM sector_benchmarks
WHERE daily_tide_id = $1
  AND sector_definition_version_id = $2
`

type GetSectorBenchmarkByTideAndDefinitionParams struct {
	DailyTideID               pgtype.UUID `json:"daily_tide_id"`
	SectorDefinitionVersionID pgtype.UUID `json:"sector_definition_version_id"`
}

func (q *Queries) GetSectorBenchmarkByTideAndDefinition(ctx context.Context, arg GetSectorBenchmarkByTideAndDefinitionParams) (SectorBenchmark, error) {
	row := q.db.QueryRow(ctx, getSectorBenchmarkByTideAndDefinition, arg.DailyTideID, arg.SectorDefinitionVersionID)
	var i SectorBenchmark
	err := row.Scan(
		&i.ID,
		&i.DailyTideID,
		&i.SectorDefinitionVersionID,
		&i.Status,
		&i.CalculationMethod,
		&i.EligibleBasketCount,
		&i.BenchmarkUnits,
		&i.MinimumRequiredBaskets,
		&i.InputChecksum,
		&i.CalculatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBasketMetric = `-- name: InsertBasketMetric :exec
INSERT INTO basket_metrics (
    id, daily_tide_id, basket_mapping_version_id, calculation_window_id, status,
    covered_weight_units, raw_return_units, expected_turbulence_units,
    normalized_performance_units, input_checksum
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10
)
`

type InsertBasketMetricParams struct {
	ID                         pgtype.UUID `json:"id"`
	DailyTideID                pgtype.UUID `json:"daily_tide_id"`
	BasketMappingVersionID     pgtype.UUID `json:"basket_mapping_version_id"`
	CalculationWindowID        pgtype.UUID `json:"calculation_window_id"`
	Status                     string      `json:"status"`
	CoveredWeightUnits         int64       `json:"covered_weight_units"`
	RawReturnUnits             *int64      `json:"raw_return_units"`
	ExpectedTurbulenceUnits    *int64      `json:"expected_turbulence_units"`
	NormalizedPerformanceUnits *int64      `json:"normalized_performance_units"`
	InputChecksum              []byte      `json:"input_checksum"`
}

func (q *Queries) InsertBasketMetric(ctx context.Context, arg InsertBasketMetricParams) error {
	_, err := q.db.Exec(ctx, insertBasketMetric,
		arg.ID,
		arg.DailyTideID,
		arg.BasketMappingVersionID,
		arg.CalculationWindowID,
		arg.Status,
		arg.CoveredWeightUnits,
		arg.RawReturnUnits,
		arg.ExpectedTurbulenceUnits,
		arg.NormalizedPerformanceUnits,
		arg.InputChecksum,
	)
	return err
}

const insertBasketMetricComponent = `-- name: InsertBasketMetricComponent :exec
INSERT INTO basket_metric_components (
    id, basket_metric_id, market_asset_id, status, target_weight_units,
    effective_weight_units, open_observation_id, close_observation_id,
    component_return_units, contribution_units, quality_flags
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
`

type InsertBasketMetricComponentParams struct {
	ID                   pgtype.UUID `json:"id"`
	BasketMetricID       pgtype.UUID `json:"basket_metric_id"`
	MarketAssetID        pgtype.UUID `json:"market_asset_id"`
	Status               string      `json:"status"`
	TargetWeightUnits    int64       `json:"target_weight_units"`
	EffectiveWeightUnits *int64      `json:"effective_weight_units"`
	OpenObservationID    pgtype.UUID `json:"open_observation_id"`
	CloseObservationID   pgtype.UUID `json:"close_observation_id"`
	ComponentReturnUnits *int64      `json:"component_return_units"`
	ContributionUnits    *int64      `json:"contribution_units"`
	QualityFlags         []byte      `json:"quality_flags"`
}

func (q *Queries) InsertBasketMetricComponent(ctx context.Context, arg InsertBasketMetricComponentParams) error {
	_, err := q.db.Exec(ctx, insertBasketMetricComponent,
		arg.ID,
		arg.BasketMetricID,
		arg.MarketAssetID,
		arg.Status,
		arg.TargetWeightUnits,
		arg.EffectiveWeightUnits,
		arg.OpenObservationID,
		arg.CloseObservationID,
		arg.ComponentReturnUnits,
		arg.ContributionUnits,
		arg.QualityFlags,
	)
	return err
}

const insertKeeperSectorResult = `-- name: InsertKeeperSectorResult :exec
INSERT INTO keeper_sector_results (
    id, daily_tide_id, keeper_definition_version_id, basket_metric_id,
    sector_benchmark_id, sector_relative_units, sector_percentile_units,
    relative_component_units, rank_component_units,
    sector_score_normalized_units, sector_score_points
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
`

type InsertKeeperSectorResultParams struct {
	ID                         pgtype.UUID `json:"id"`
	DailyTideID                pgtype.UUID `json:"daily_tide_id"`
	KeeperDefinitionVersionID  pgtype.UUID `json:"keeper_definition_version_id"`
	BasketMetricID             pgtype.UUID `json:"basket_metric_id"`
	SectorBenchmarkID          pgtype.UUID `json:"sector_benchmark_id"`
	SectorRelativeUnits        int64       `json:"sector_relative_units"`
	SectorPercentileUnits      int64       `json:"sector_percentile_units"`
	RelativeComponentUnits     int64       `json:"relative_component_units"`
	RankComponentUnits         int64       `json:"rank_component_units"`
	SectorScoreNormalizedUnits int64       `json:"sector_score_normalized_units"`
	SectorScorePoints          int64       `json:"sector_score_points"`
}

func (q *Queries) InsertKeeperSectorResult(ctx context.Context, arg InsertKeeperSectorResultParams) error {
	_, err := q.db.Exec(ctx, insertKeeperSectorResult,
		arg.ID,
		arg.DailyTideID,
		arg.KeeperDefinitionVersionID,
		arg.BasketMetricID,
		arg.SectorBenchmarkID,
		arg.SectorRelativeUnits,
		arg.SectorPercentileUnits,
		arg.RelativeComponentUnits,
		arg.RankComponentUnits,
		arg.SectorScoreNormalizedUnits,
		arg.SectorScorePoints,
	)
	return err
}

const insertMarketCalculationWindow = `-- name: InsertMarketCalculationWindow :exec
INSERT INTO market_calculation_windows (
    id, daily_tide_id, provider_key, data_window_start, data_window_end,
    required_granularity_seconds, observation_tolerance_seconds
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
`

type InsertMarketCalculationWindowParams struct {
	ID                          pgtype.UUID        `json:"id"`
	DailyTideID                 pgtype.UUID        `json:"daily_tide_id"`
	ProviderKey                 string             `json:"provider_key"`
	DataWindowStart             pgtype.Timestamptz `json:"data_window_start"`
	DataWindowEnd               pgtype.Timestamptz `json:"data_window_end"`
	RequiredGranularitySeconds  int32              `json:"required_granularity_seconds"`
	ObservationToleranceSeconds int32              `json:"observation_tolerance_seconds"`
}

func (q *Queries) InsertMarketCalculationWindow(ctx context.Context, arg InsertMarketCalculationWindowParams) error {
	_, err := q.db.Exec(ctx, insertMarketCalculationWindow,
		arg.ID,
		arg.DailyTideID,
		arg.ProviderKey,
		arg.DataWindowStart,
		arg.DataWindowEnd,
		arg.RequiredGranularitySeconds,
		arg.ObservationToleranceSeconds,
	)
	return err
}

const insertMarketPriceObservation = `-- name: InsertMarketPriceObservation :exec
INSERT INTO market_price_observations (
    id, calculation_window_id, market_asset_id, observed_at, raw_price,
    price, quality_status, quality_flags, raw_response_hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertMarketPriceObservationParams struct {
	ID                  pgtype.UUID        `json:"id"`
	CalculationWindowID pgtype.UUID        `json:"calculation_window_id"`
	MarketAssetID       pgtype.UUID        `json:"market_asset_id"`
	ObservedAt          pgtype.Timestamptz `json:"observed_at"`
	RawPrice            string             `json:"raw_price"`
	Price               pgtype.Numeric     `json:"price"`
	QualityStatus       string             `json:"quality_status"`
	QualityFlags        []byte             `json:"quality_flags"`
	RawResponseHash     []byte             `json:"raw_response_hash"`
}

func (q *Queries) InsertMarketPriceObservation(ctx context.Context, arg InsertMarketPriceObservationParams) error {
	_, err := q.db.Exec(ctx, insertMarketPriceObservation,
		arg.ID,
		arg.CalculationWindowID,
		arg.MarketAssetID,
		arg.ObservedAt,
		arg.RawPrice,
		arg.Price,
		arg.QualityStatus,
		arg.QualityFlags,
		arg.RawResponseHash,
	)
	return err
}

const insertSectorBenchmark = `-- name: InsertSectorBenchmark :exec
INSERT INTO sector_benchmarks (
    id, daily_tide_id, sector_definition_version_id, status, calculation_method,
    eligible_basket_count, benchmark_units, minimum_required_baskets, input_checksum
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertSectorBenchmarkParams struct {
	ID                        pgtype.UUID `json:"id"`
	DailyTideID               pgtype.UUID `json:"daily_tide_id"`
	SectorDefinitionVersionID pgtype.UUID `json:"sector_definition_version_id"`
	Status                    string      `json:"status"`
	CalculationMethod         string      `json:"calculation_method"`
	EligibleBasketCount       int32       `json:"eligible_basket_count"`
	BenchmarkUnits            *int64      `json:"benchmark_units"`
	MinimumRequiredBaskets    int32       `json:"minimum_required_baskets"`
	InputChecksum             []byte      `json:"input_checksum"`
}

func (q *Queries) InsertSectorBenchmark(ctx context.Context, arg InsertSectorBenchmarkParams) error {
	_, err := q.db.Exec(ctx, insertSectorBenchmark,
		arg.ID,
		arg.DailyTideID,
		arg.SectorDefinitionVersionID,
		arg.Status,
		arg.CalculationMethod,
		arg.EligibleBasketCount,
		arg.BenchmarkUnits,
		arg.MinimumRequiredBaskets,
		arg.InputChecksum,
	)
	return err
}

const insertSectorBenchmarkMember = `-- name: InsertSectorBenchmarkMember :exec
INSERT INTO sector_benchmark_members (
    id, sector_benchmark_id, basket_metric_id, benchmark_weight_units,
    normalized_performance_units, contribution_units, rank_index_units,
    rank_percentile_units
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8
)
`

type InsertSectorBenchmarkMemberParams struct {
	ID                         pgtype.UUID `json:"id"`
	SectorBenchmarkID          pgtype.UUID `json:"sector_benchmark_id"`
	BasketMetricID             pgtype.UUID `json:"basket_metric_id"`
	BenchmarkWeightUnits       int64       `json:"benchmark_weight_units"`
	NormalizedPerformanceUnits int64       `json:"normalized_performance_units"`
	ContributionUnits          int64       `json:"contribution_units"`
	RankIndexUnits             int64       `json:"rank_index_units"`
	RankPercentileUnits        int64       `json:"rank_percentile_units"`
}

func (q *Queries) InsertSectorBenchmarkMember(ctx context.Context, arg InsertSectorBenchmarkMemberParams) error {
	_, err := q.db.Exec(ctx, insertSectorBenchmarkMember,
		arg.ID,
		arg.SectorBenchmarkID,
		arg.BasketMetricID,
		arg.BenchmarkWeightUnits,
		arg.NormalizedPerformanceUnits,
		arg.ContributionUnits,
		arg.RankIndexUnits,
		arg.RankPercentileUnits,
	)
	return err
}

const listBasketCalculationMappingComponents = `-- name: ListBasketCalculationMappingComponents :many
SELECT component.basket_mapping_version_id, component.market_asset_id, component.weight,
       component.created_at
FROM basket_mapping_components AS component
WHERE component.basket_mapping_version_id = $1
ORDER BY component.market_asset_id ASC
`

func (q *Queries) ListBasketCalculationMappingComponents(ctx context.Context, basketMappingVersionID pgtype.UUID) ([]BasketMappingComponent, error) {
	rows, err := q.db.Query(ctx, listBasketCalculationMappingComponents, basketMappingVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BasketMappingComponent{}
	for rows.Next() {
		var i BasketMappingComponent
		if err := rows.Scan(
			&i.BasketMappingVersionID,
			&i.MarketAssetID,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBasketMetricComponents = `-- name: ListBasketMetricComponents :many
SELECT id, basket_metric_id, market_asset_id, status, target_weight_units,
       effective_weight_units, open_observation_id, close_observation_id,
       component_return_units, contribution_units, quality_flags, created_at
FROM basket_metric_components
WHERE basket_metric_id = $1
ORDER BY market_asset_id ASC
`

func (q *Queries) ListBasketMetricComponents(ctx context.Context, basketMetricID pgtype.UUID) ([]BasketMetricComponent, error) {
	rows, err := q.db.Query(ctx, listBasketMetricComponents, basketMetricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BasketMetricComponent{}
	for rows.Next() {
		var i BasketMetricComponent
		if err := rows.Scan(
			&i.ID,
			&i.BasketMetricID,
			&i.MarketAssetID,
			&i.Status,
			&i.TargetWeightUnits,
			&i.EffectiveWeightUnits,
			&i.OpenObservationID,
			&i.CloseObservationID,
			&i.ComponentReturnUnits,
			&i.ContributionUnits,
			&i.QualityFlags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketPriceObservationsForAsset = `-- name: ListMarketPriceObservationsForAsset :many
SELECT id, calculation_window_id, market_asset_id, observed_at, raw_price, price,
       quality_status, quality_flags, raw_response_hash, created_at
FROM market_price_observations
WHERE calculation_window_id = $1
  AND market_asset_id = $2
ORDER BY observed_at ASC, id ASC
`

type ListMarketPriceObservationsForAssetParams struct {
	CalculationWindowID pgtype.UUID `json:"calculation_window_id"`
	MarketAssetID       pgtype.UUID `json:"market_asset_id"`
}

func (q *Queries) ListMarketPriceObservationsForAsset(ctx context.Context, arg ListMarketPriceObservationsForAssetParams) ([]MarketPriceObservation, error) {
	rows, err := q.db.Query(ctx, listMarketPriceObservationsForAsset, arg.CalculationWindowID, arg.MarketAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketPriceObservation{}
	for rows.Next() {
		var i MarketPriceObservation
		if err := rows.Scan(
			&i.ID,
			&i.CalculationWindowID,
			&i.MarketAssetID,
			&i.ObservedAt,
			&i.RawPrice,
			&i.Price,
			&i.QualityStatus,
			&i.QualityFlags,
			&i.RawResponseHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyBasketMetricsForSectorBenchmark = `-- name: ListReadyBasketMetricsForSectorBenchmark :many
SELECT metric.id, metric.daily_tide_id, metric.basket_mapping_version_id,
       metric.calculation_window_id, metric.status, metric.covered_weight_units,
       metric.raw_return_units, metric.expected_turbulence_units,
       metric.normalized_performance_units, metric.input_checksum,
       metric.calculated_at, metric.created_at
FROM basket_metrics AS metric
JOIN basket_mapping_versions AS mapping
    ON mapping.id = metric.basket_mapping_version_id
WHERE metric.daily_tide_id = $1
  AND mapping.sector_definition_version_id = $2
  AND mapping.benchmark_eligible = true
  AND metric.status = 'READY'
ORDER BY metric.basket_mapping_version_id ASC
`

type ListReadyBasketMetricsForSectorBenchmarkParams struct {
	DailyTideID               pgtype.UUID `json:"daily_tide_id"`
	SectorDefinitionVersionID pgtype.UUID `json:"sector_definition_version_id"`
}

func (q *Queries) ListReadyBasketMetricsForSectorBenchmark(ctx context.Context, arg ListReadyBasketMetricsForSectorBenchmarkParams) ([]BasketMetric, error) {
	rows, err := q.db.Query(ctx, listReadyBasketMetricsForSectorBenchmark, arg.DailyTideID, arg.SectorDefinitionVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BasketMetric{}
	for rows.Next() {
		var i BasketMetric
		if err := rows.Scan(
			&i.ID,
			&i.DailyTideID,
			&i.BasketMappingVersionID,
			&i.CalculationWindowID,
			&i.Status,
			&i.CoveredWeightUnits,
			&i.RawReturnUnits,
			&i.ExpectedTurbulenceUnits,
			&i.NormalizedPerformanceUnits,
			&i.InputChecksum,
			&i.CalculatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectorBenchmarkMembers = `-- name: ListSectorBenchmarkMembers :many
SELECT id, sector_benchmark_id, basket_metric_id, benchmark_weight_units,
       normalized_performance_units, contribution_units, rank_index_units,
       rank_percentile_units, created_at
FROM sector_benchmark_members
WHERE sector_benchmark_id = $1
ORDER BY rank_index_units ASC, basket_metric_id ASC
`

func (q *Queries) ListSectorBenchmarkMembers(ctx context.Context, sectorBenchmarkID pgtype.UUID) ([]SectorBenchmarkMember, error) {
	rows, err := q.db.Query(ctx, listSectorBenchmarkMembers, sectorBenchmarkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SectorBenchmarkMember{}
	for rows.Next() {
		var i SectorBenchmarkMember
		if err := rows.Scan(
			&i.ID,
			&i.SectorBenchmarkID,
			&i.BasketMetricID,
			&i.BenchmarkWeightUnits,
			&i.NormalizedPerformanceUnits,
			&i.ContributionUnits,
			&i.RankIndexUnits,
			&i.RankPercentileUnits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetBasketCalculationMappingsForContent = `-- name: ListTargetBasketCalculationMappingsForContent :many
SELECT mapping.id, mapping.mapping_key, mapping.content_version, mapping.sector_definition_version_id,
       mapping.minimum_covered_weight_units, mapping.expected_turbulence_policy_id,
       mapping.normalization_cap_units, mapping.benchmark_eligible
FROM basket_mapping_versions AS mapping
JOIN sector_definition_versions AS definition
    ON definition.id = mapping.sector_definition_version_id
WHERE mapping.content_version = $1
ORDER BY definition.sector_key ASC, mapping.id ASC
`

type ListTargetBasketCalculationMappingsForContentRow struct {
	ID                         pgtype.UUID `json:"id"`
	MappingKey                 string      `json:"mapping_key"`
	ContentVersion             int64       `json:"content_version"`
	SectorDefinitionVersionID  pgtype.UUID `json:"sector_definition_version_id"`
	MinimumCoveredWeightUnits  *int64      `json:"minimum_covered_weight_units"`
	ExpectedTurbulencePolicyID pgtype.UUID `json:"expected_turbulence_policy_id"`
	NormalizationCapUnits      *int64      `json:"normalization_cap_units"`
	BenchmarkEligible          *bool       `json:"benchmark_eligible"`
}

func (q *Queries) ListTargetBasketCalculationMappingsForContent(ctx context.Context, contentVersion int64) ([]ListTargetBasketCalculationMappingsForContentRow, error) {
	rows, err := q.db.Query(ctx, listTargetBasketCalculationMappingsForContent, contentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetBasketCalculationMappingsForContentRow{}
	for rows.Next() {
		var i ListTargetBasketCalculationMappingsForContentRow
		if err := rows.Scan(
			&i.ID,
			&i.MappingKey,
			&i.ContentVersion,
			&i.SectorDefinitionVersionID,
			&i.MinimumCoveredWeightUnits,
			&i.ExpectedTurbulencePolicyID,
			&i.NormalizationCapUnits,
			&i.BenchmarkEligible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetSectorBenchmarkReadiness = `-- name: ListTargetSectorBenchmarkReadiness :many
SELECT definition.sector_key, benchmark.status, benchmark.eligible_basket_count,
       definition.minimum_eligible_baskets AS minimum_required_baskets, benchmark.id AS sector_benchmark_id
FROM sector_definition_versions AS definition
LEFT JOIN sector_benchmarks AS benchmark
    ON benchmark.sector_definition_version_id = definition.id
   AND benchmark.daily_tide_id = $1
WHERE definition.content_version = $2
ORDER BY definition.sector_key ASC
`

type ListTargetSectorBenchmarkReadinessParams struct {
	DailyTideID    pgtype.UUID `json:"daily_tide_id"`
	ContentVersion int64       `json:"content_version"`
}

type ListTargetSectorBenchmarkReadinessRow struct {
	SectorKey              string      `json:"sector_key"`
	Status                 *string     `json:"status"`
	EligibleBasketCount    *int32      `json:"eligible_basket_count"`
	MinimumRequiredBaskets int32       `json:"minimum_required_baskets"`
	SectorBenchmarkID      pgtype.UUID `json:"sector_benchmark_id"`
}

func (q *Queries) ListTargetSectorBenchmarkReadiness(ctx context.Context, arg ListTargetSectorBenchmarkReadinessParams) ([]ListTargetSectorBenchmarkReadinessRow, error) {
	rows, err := q.db.Query(ctx, listTargetSectorBenchmarkReadiness, arg.DailyTideID, arg.ContentVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetSectorBenchmarkReadinessRow{}
	for rows.Next() {
		var i ListTargetSectorBenchmarkReadinessRow
		if err := rows.Scan(
			&i.SectorKey,
			&i.Status,
			&i.EligibleBasketCount,
			&i.MinimumRequiredBaskets,
			&i.SectorBenchmarkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
