// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthenticatedSession = `-- name: GetAuthenticatedSession :one
SELECT
    s.id AS session_id,
    s.account_id,
    s.player_id,
    s.expires_at,
    transaction_timestamp()::timestamptz AS authenticated_at
FROM sessions AS s
JOIN accounts AS a
    ON a.id = s.account_id
   AND a.status = 'ACTIVE'
JOIN players AS p
    ON p.id = s.player_id
   AND p.account_id = s.account_id
WHERE s.token_digest = $1
  AND s.expires_at > transaction_timestamp()
  AND s.revoked_at IS NULL
  AND s.rotated_at IS NULL
  AND s.replaced_by_session_id IS NULL
`

type GetAuthenticatedSessionRow struct {
	SessionID       pgtype.UUID        `json:"session_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	PlayerID        pgtype.UUID        `json:"player_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthenticatedAt pgtype.Timestamptz `json:"authenticated_at"`
}

func (q *Queries) GetAuthenticatedSession(ctx context.Context, tokenDigest []byte) (GetAuthenticatedSessionRow, error) {
	row := q.db.QueryRow(ctx, getAuthenticatedSession, tokenDigest)
	var i GetAuthenticatedSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.AccountID,
		&i.PlayerID,
		&i.ExpiresAt,
		&i.AuthenticatedAt,
	)
	return i, err
}
