// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: voyages.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (player_id, scope, key, state, request_hash)
VALUES ($1, $2, $3, 'IN_PROGRESS', $4)
ON CONFLICT (player_id, scope, key) DO NOTHING
RETURNING player_id, scope, key, state, request_hash, result_voyage_id,
          response_status, response_json, created_at, completed_at
`

type ClaimIdempotencyKeyParams struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	Scope       string      `json:"scope"`
	Key         string      `json:"key"`
	RequestHash []byte      `json:"request_hash"`
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.PlayerID,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.PlayerID,
		&i.Scope,
		&i.Key,
		&i.State,
		&i.RequestHash,
		&i.ResultVoyageID,
		&i.ResponseStatus,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET state = 'COMPLETED',
    result_voyage_id = $1,
    response_status = $2,
    response_json = $3,
    completed_at = transaction_timestamp()
WHERE player_id = $4
  AND scope = $5
  AND key = $6
`

type CompleteIdempotencyKeyParams struct {
	ResultVoyageID pgtype.UUID `json:"result_voyage_id"`
	ResponseStatus *int16      `json:"response_status"`
	ResponseJson   []byte      `json:"response_json"`
	PlayerID       pgtype.UUID `json:"player_id"`
	Scope          string      `json:"scope"`
	Key            string      `json:"key"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResultVoyageID,
		arg.ResponseStatus,
		arg.ResponseJson,
		arg.PlayerID,
		arg.Scope,
		arg.Key,
	)
	return err
}

const getActiveVoyageForPlayer = `-- name: GetActiveVoyageForPlayer :one
SELECT v.id, v.public_id, v.player_id, v.status, v.voyage_definition_version_id,
       v.current_day_number, v.fund_health, v.max_fund_health, v.capital, v.score,
       v.row_version, v.started_at, v.completed_at, v.created_at, v.updated_at
FROM voyages AS v
WHERE v.player_id = $1
  AND v.status = 'ACTIVE'
`

type GetActiveVoyageForPlayerRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveVoyageForPlayer(ctx context.Context, playerID pgtype.UUID) (GetActiveVoyageForPlayerRow, error) {
	row := q.db.QueryRow(ctx, getActiveVoyageForPlayer, playerID)
	var i GetActiveVoyageForPlayerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentVoyageForPlayer = `-- name: GetCurrentVoyageForPlayer :one
SELECT v.id, v.public_id, v.player_id, v.status, v.voyage_definition_version_id,
       v.current_day_number, v.fund_health, v.max_fund_health, v.capital, v.score,
       v.row_version, v.started_at, v.completed_at, v.created_at, v.updated_at
FROM voyages AS v
JOIN players AS p ON p.current_voyage_id = v.id AND p.id = v.player_id
WHERE p.id = $1
`

type GetCurrentVoyageForPlayerRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCurrentVoyageForPlayer(ctx context.Context, playerID pgtype.UUID) (GetCurrentVoyageForPlayerRow, error) {
	row := q.db.QueryRow(ctx, getCurrentVoyageForPlayer, playerID)
	var i GetCurrentVoyageForPlayerRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKeyForUpdate = `-- name: GetIdempotencyKeyForUpdate :one
SELECT player_id, scope, key, state, request_hash, result_voyage_id,
       response_status, response_json, created_at, completed_at
FROM idempotency_keys
WHERE player_id = $1
  AND scope = $2
  AND key = $3
FOR UPDATE
`

type GetIdempotencyKeyForUpdateParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Scope    string      `json:"scope"`
	Key      string      `json:"key"`
}

func (q *Queries) GetIdempotencyKeyForUpdate(ctx context.Context, arg GetIdempotencyKeyForUpdateParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyForUpdate, arg.PlayerID, arg.Scope, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.PlayerID,
		&i.Scope,
		&i.Key,
		&i.State,
		&i.RequestHash,
		&i.ResultVoyageID,
		&i.ResponseStatus,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOpenDailyTide = `-- name: GetOpenDailyTide :one
SELECT id, day_key, sequence_number, phase, lock_at, settle_after, content_version, created_at, updated_at
FROM daily_tides
WHERE day_key = $1
  AND lock_at > transaction_timestamp()
LIMIT 1
`

func (q *Queries) GetOpenDailyTide(ctx context.Context, dayKey pgtype.Date) (DailyTide, error) {
	row := q.db.QueryRow(ctx, getOpenDailyTide, dayKey)
	var i DailyTide
	err := row.Scan(
		&i.ID,
		&i.DayKey,
		&i.SequenceNumber,
		&i.Phase,
		&i.LockAt,
		&i.SettleAfter,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedVoyageDefinition = `-- name: GetPublishedVoyageDefinition :one
SELECT id, definition_key, version, status, duration_days,
       starting_hull, starting_supplies, fleet_slot_count, initial_phase,
       launch_presentation, checksum, published_at, created_at
FROM voyage_definition_versions
WHERE definition_key = $1
  AND status = 'PUBLISHED'
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetPublishedVoyageDefinition(ctx context.Context, definitionKey string) (VoyageDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getPublishedVoyageDefinition, definitionKey)
	var i VoyageDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.DefinitionKey,
		&i.Version,
		&i.Status,
		&i.DurationDays,
		&i.StartingHull,
		&i.StartingSupplies,
		&i.FleetSlotCount,
		&i.InitialPhase,
		&i.LaunchPresentation,
		&i.Checksum,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVoyageByPublicID = `-- name: GetVoyageByPublicID :one
SELECT id, public_id, player_id, status, voyage_definition_version_id,
       current_day_number, fund_health, max_fund_health, capital, score,
       row_version, started_at, completed_at, created_at, updated_at
FROM voyages
WHERE public_id = $1
`

type GetVoyageByPublicIDRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVoyageByPublicID(ctx context.Context, publicID string) (GetVoyageByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getVoyageByPublicID, publicID)
	var i GetVoyageByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoyageByPublicIDAndPlayerID = `-- name: GetVoyageByPublicIDAndPlayerID :one
SELECT id, public_id, player_id, status, voyage_definition_version_id,
       current_day_number, fund_health, max_fund_health, capital, score,
       row_version, started_at, completed_at, created_at, updated_at
FROM voyages
WHERE public_id = $1
  AND player_id = $2
`

type GetVoyageByPublicIDAndPlayerIDParams struct {
	PublicID string      `json:"public_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

type GetVoyageByPublicIDAndPlayerIDRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVoyageByPublicIDAndPlayerID(ctx context.Context, arg GetVoyageByPublicIDAndPlayerIDParams) (GetVoyageByPublicIDAndPlayerIDRow, error) {
	row := q.db.QueryRow(ctx, getVoyageByPublicIDAndPlayerID, arg.PublicID, arg.PlayerID)
	var i GetVoyageByPublicIDAndPlayerIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoyageDefinitionByID = `-- name: GetVoyageDefinitionByID :one
SELECT id, definition_key, version, status, duration_days,
       starting_hull, starting_supplies, fleet_slot_count, initial_phase,
       launch_presentation, checksum, published_at, created_at
FROM voyage_definition_versions
WHERE id = $1
`

func (q *Queries) GetVoyageDefinitionByID(ctx context.Context, id pgtype.UUID) (VoyageDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, getVoyageDefinitionByID, id)
	var i VoyageDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.DefinitionKey,
		&i.Version,
		&i.Status,
		&i.DurationDays,
		&i.StartingHull,
		&i.StartingSupplies,
		&i.FleetSlotCount,
		&i.InitialPhase,
		&i.LaunchPresentation,
		&i.Checksum,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVoyageDefinitionInitialOffers = `-- name: GetVoyageDefinitionInitialOffers :many
SELECT vo.voyage_definition_version_id, vo.keeper_definition_version_id, vo.position, vo.cost,
       k.keeper_key, k.name, k.current_key, k.current_name,
       k.sector_key, k.role_key, k.rarity_key, k.passive_rule_key,
       k.passive_rule_config
FROM voyage_definition_initial_shop_offers AS vo
JOIN keeper_definition_versions AS k ON k.id = vo.keeper_definition_version_id
WHERE vo.voyage_definition_version_id = $1
ORDER BY vo.position
`

type GetVoyageDefinitionInitialOffersRow struct {
	VoyageDefinitionVersionID pgtype.UUID `json:"voyage_definition_version_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	Position                  int16       `json:"position"`
	Cost                      int32       `json:"cost"`
	KeeperKey                 string      `json:"keeper_key"`
	Name                      string      `json:"name"`
	CurrentKey                string      `json:"current_key"`
	CurrentName               string      `json:"current_name"`
	SectorKey                 string      `json:"sector_key"`
	RoleKey                   string      `json:"role_key"`
	RarityKey                 string      `json:"rarity_key"`
	PassiveRuleKey            string      `json:"passive_rule_key"`
	PassiveRuleConfig         []byte      `json:"passive_rule_config"`
}

func (q *Queries) GetVoyageDefinitionInitialOffers(ctx context.Context, voyageDefinitionVersionID pgtype.UUID) ([]GetVoyageDefinitionInitialOffersRow, error) {
	rows, err := q.db.Query(ctx, getVoyageDefinitionInitialOffers, voyageDefinitionVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoyageDefinitionInitialOffersRow{}
	for rows.Next() {
		var i GetVoyageDefinitionInitialOffersRow
		if err := rows.Scan(
			&i.VoyageDefinitionVersionID,
			&i.KeeperDefinitionVersionID,
			&i.Position,
			&i.Cost,
			&i.KeeperKey,
			&i.Name,
			&i.CurrentKey,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
			&i.PassiveRuleKey,
			&i.PassiveRuleConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoyageDefinitionStarterKeepers = `-- name: GetVoyageDefinitionStarterKeepers :many
SELECT vk.voyage_definition_version_id, vk.keeper_definition_version_id, vk.position,
       k.keeper_key, k.name, k.current_key, k.current_name,
       k.sector_key, k.role_key, k.rarity_key, k.passive_rule_key,
       k.passive_rule_config,
       n.node_key AS root_upgrade_node_key
FROM voyage_definition_starter_keepers AS vk
JOIN keeper_definition_versions AS k ON k.id = vk.keeper_definition_version_id
JOIN keeper_definition_upgrade_nodes AS n
    ON n.keeper_definition_version_id = k.id
   AND n.is_root
WHERE vk.voyage_definition_version_id = $1
ORDER BY vk.position
`

type GetVoyageDefinitionStarterKeepersRow struct {
	VoyageDefinitionVersionID pgtype.UUID `json:"voyage_definition_version_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	Position                  int16       `json:"position"`
	KeeperKey                 string      `json:"keeper_key"`
	Name                      string      `json:"name"`
	CurrentKey                string      `json:"current_key"`
	CurrentName               string      `json:"current_name"`
	SectorKey                 string      `json:"sector_key"`
	RoleKey                   string      `json:"role_key"`
	RarityKey                 string      `json:"rarity_key"`
	PassiveRuleKey            string      `json:"passive_rule_key"`
	PassiveRuleConfig         []byte      `json:"passive_rule_config"`
	RootUpgradeNodeKey        string      `json:"root_upgrade_node_key"`
}

func (q *Queries) GetVoyageDefinitionStarterKeepers(ctx context.Context, voyageDefinitionVersionID pgtype.UUID) ([]GetVoyageDefinitionStarterKeepersRow, error) {
	rows, err := q.db.Query(ctx, getVoyageDefinitionStarterKeepers, voyageDefinitionVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoyageDefinitionStarterKeepersRow{}
	for rows.Next() {
		var i GetVoyageDefinitionStarterKeepersRow
		if err := rows.Scan(
			&i.VoyageDefinitionVersionID,
			&i.KeeperDefinitionVersionID,
			&i.Position,
			&i.KeeperKey,
			&i.Name,
			&i.CurrentKey,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
			&i.PassiveRuleKey,
			&i.PassiveRuleConfig,
			&i.RootUpgradeNodeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertKeeperInstance = `-- name: InsertKeeperInstance :exec
INSERT INTO keeper_instances (id, public_id, voyage_id, keeper_definition_version_id,
                              upgrade_node_key, acquired_day, acquired_source)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7)
`

type InsertKeeperInstanceParams struct {
	ID                        pgtype.UUID `json:"id"`
	PublicID                  string      `json:"public_id"`
	VoyageID                  pgtype.UUID `json:"voyage_id"`
	KeeperDefinitionVersionID pgtype.UUID `json:"keeper_definition_version_id"`
	UpgradeNodeKey            string      `json:"upgrade_node_key"`
	AcquiredDay               int16       `json:"acquired_day"`
	AcquiredSource            string      `json:"acquired_source"`
}

func (q *Queries) InsertKeeperInstance(ctx context.Context, arg InsertKeeperInstanceParams) error {
	_, err := q.db.Exec(ctx, insertKeeperInstance,
		arg.ID,
		arg.PublicID,
		arg.VoyageID,
		arg.KeeperDefinitionVersionID,
		arg.UpgradeNodeKey,
		arg.AcquiredDay,
		arg.AcquiredSource,
	)
	return err
}

const insertPlayerDailyStateWithView = `-- name: InsertPlayerDailyStateWithView :exec
WITH inserted_state AS (
    INSERT INTO player_daily_states (id, player_id, voyage_id, daily_tide_id, day_number, phase, version)
    VALUES ($2, $3, $4,
            $5, 1, 'PREPARATION', 1)
    RETURNING id
)
INSERT INTO player_daily_context_views (player_daily_state_id, schema_version, projection)
VALUES ((SELECT id FROM inserted_state), 1, $1)
`

type InsertPlayerDailyStateWithViewParams struct {
	Projection  []byte      `json:"projection"`
	StateID     pgtype.UUID `json:"state_id"`
	PlayerID    pgtype.UUID `json:"player_id"`
	VoyageID    pgtype.UUID `json:"voyage_id"`
	DailyTideID pgtype.UUID `json:"daily_tide_id"`
}

func (q *Queries) InsertPlayerDailyStateWithView(ctx context.Context, arg InsertPlayerDailyStateWithViewParams) error {
	_, err := q.db.Exec(ctx, insertPlayerDailyStateWithView,
		arg.Projection,
		arg.StateID,
		arg.PlayerID,
		arg.VoyageID,
		arg.DailyTideID,
	)
	return err
}

const insertVoyage = `-- name: InsertVoyage :one
INSERT INTO voyages (
    id, public_id, player_id, status, voyage_definition_version_id,
    current_day_number, fund_health, max_fund_health, capital, score,
    row_version, started_at
) VALUES (
    $1, $2, $3, 'ACTIVE',
    $4,
    1, $5, $6, $7,
    '0.0000', 1, transaction_timestamp()
)
RETURNING id, public_id, player_id, status, voyage_definition_version_id,
          current_day_number, fund_health, max_fund_health, capital, score,
          row_version, started_at, completed_at, created_at, updated_at
`

type InsertVoyageParams struct {
	ID                        pgtype.UUID `json:"id"`
	PublicID                  string      `json:"public_id"`
	PlayerID                  pgtype.UUID `json:"player_id"`
	VoyageDefinitionVersionID pgtype.UUID `json:"voyage_definition_version_id"`
	FundHealth                int32       `json:"fund_health"`
	MaxFundHealth             int32       `json:"max_fund_health"`
	Capital                   int32       `json:"capital"`
}

type InsertVoyageRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertVoyage(ctx context.Context, arg InsertVoyageParams) (InsertVoyageRow, error) {
	row := q.db.QueryRow(ctx, insertVoyage,
		arg.ID,
		arg.PublicID,
		arg.PlayerID,
		arg.VoyageDefinitionVersionID,
		arg.FundHealth,
		arg.MaxFundHealth,
		arg.Capital,
	)
	var i InsertVoyageRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVoyageLedgerEntry = `-- name: InsertVoyageLedgerEntry :exec
INSERT INTO voyage_ledger_entries (id, voyage_id, entry_type, amount, balance_after,
                                    source_type, source_id, reason_key)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
`

type InsertVoyageLedgerEntryParams struct {
	ID           pgtype.UUID `json:"id"`
	VoyageID     pgtype.UUID `json:"voyage_id"`
	EntryType    string      `json:"entry_type"`
	Amount       int32       `json:"amount"`
	BalanceAfter int32       `json:"balance_after"`
	SourceType   string      `json:"source_type"`
	SourceID     string      `json:"source_id"`
	ReasonKey    string      `json:"reason_key"`
}

func (q *Queries) InsertVoyageLedgerEntry(ctx context.Context, arg InsertVoyageLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertVoyageLedgerEntry,
		arg.ID,
		arg.VoyageID,
		arg.EntryType,
		arg.Amount,
		arg.BalanceAfter,
		arg.SourceType,
		arg.SourceID,
		arg.ReasonKey,
	)
	return err
}

const insertVoyageLifecycleEvent = `-- name: InsertVoyageLifecycleEvent :exec
INSERT INTO voyage_lifecycle_events (id, public_id, voyage_id, event_type, resulting_status)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertVoyageLifecycleEventParams struct {
	ID              pgtype.UUID `json:"id"`
	PublicID        string      `json:"public_id"`
	VoyageID        pgtype.UUID `json:"voyage_id"`
	EventType       string      `json:"event_type"`
	ResultingStatus string      `json:"resulting_status"`
}

func (q *Queries) InsertVoyageLifecycleEvent(ctx context.Context, arg InsertVoyageLifecycleEventParams) error {
	_, err := q.db.Exec(ctx, insertVoyageLifecycleEvent,
		arg.ID,
		arg.PublicID,
		arg.VoyageID,
		arg.EventType,
		arg.ResultingStatus,
	)
	return err
}

const listLifecycleEventsForVoyage = `-- name: ListLifecycleEventsForVoyage :many
SELECT id, public_id, voyage_id, event_type, resulting_status, occurred_at, created_at
FROM voyage_lifecycle_events
WHERE voyage_id = $1
ORDER BY occurred_at, id
`

func (q *Queries) ListLifecycleEventsForVoyage(ctx context.Context, voyageID pgtype.UUID) ([]VoyageLifecycleEvent, error) {
	rows, err := q.db.Query(ctx, listLifecycleEventsForVoyage, voyageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoyageLifecycleEvent{}
	for rows.Next() {
		var i VoyageLifecycleEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.VoyageID,
			&i.EventType,
			&i.ResultingStatus,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyageKeepers = `-- name: ListVoyageKeepers :many
SELECT
    v.id AS voyage_id,
    v.public_id AS voyage_public_id,
    i.public_id AS keeper_public_id,
    d.keeper_key AS definition_key,
    d.content_version AS definition_version,
    d.name,
    d.current_name,
    d.sector_key,
    d.role_key,
    d.rarity_key,
    n.depth AS node_depth,
    i.upgrade_node_key,
    i.acquired_day,
    i.acquired_source,
    i.acquired_at
FROM voyages AS v
JOIN keeper_instances AS i ON i.voyage_id = v.id
JOIN keeper_definition_versions AS d ON d.id = i.keeper_definition_version_id
JOIN keeper_definition_upgrade_nodes AS n
    ON n.keeper_definition_version_id = i.keeper_definition_version_id
   AND n.node_key = i.upgrade_node_key
WHERE v.id = $1
ORDER BY i.acquired_day ASC, i.acquired_at ASC, i.id ASC
`

type ListVoyageKeepersRow struct {
	VoyageID          pgtype.UUID        `json:"voyage_id"`
	VoyagePublicID    string             `json:"voyage_public_id"`
	KeeperPublicID    string             `json:"keeper_public_id"`
	DefinitionKey     string             `json:"definition_key"`
	DefinitionVersion int64              `json:"definition_version"`
	Name              string             `json:"name"`
	CurrentName       string             `json:"current_name"`
	SectorKey         string             `json:"sector_key"`
	RoleKey           string             `json:"role_key"`
	RarityKey         string             `json:"rarity_key"`
	NodeDepth         int16              `json:"node_depth"`
	UpgradeNodeKey    string             `json:"upgrade_node_key"`
	AcquiredDay       int16              `json:"acquired_day"`
	AcquiredSource    string             `json:"acquired_source"`
	AcquiredAt        pgtype.Timestamptz `json:"acquired_at"`
}

func (q *Queries) ListVoyageKeepers(ctx context.Context, voyageID pgtype.UUID) ([]ListVoyageKeepersRow, error) {
	rows, err := q.db.Query(ctx, listVoyageKeepers, voyageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoyageKeepersRow{}
	for rows.Next() {
		var i ListVoyageKeepersRow
		if err := rows.Scan(
			&i.VoyageID,
			&i.VoyagePublicID,
			&i.KeeperPublicID,
			&i.DefinitionKey,
			&i.DefinitionVersion,
			&i.Name,
			&i.CurrentName,
			&i.SectorKey,
			&i.RoleKey,
			&i.RarityKey,
			&i.NodeDepth,
			&i.UpgradeNodeKey,
			&i.AcquiredDay,
			&i.AcquiredSource,
			&i.AcquiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlayerRow = `-- name: LockPlayerRow :one
SELECT id, account_id, public_id, onboarding_completed, locale, timezone,
       current_voyage_id, created_at, updated_at
FROM players
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPlayerRow(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, lockPlayerRow, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublicID,
		&i.OnboardingCompleted,
		&i.Locale,
		&i.Timezone,
		&i.CurrentVoyageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockVoyageRowForUpdate = `-- name: LockVoyageRowForUpdate :one
SELECT id, public_id, player_id, status, voyage_definition_version_id,
       current_day_number, fund_health, max_fund_health, capital, score,
       row_version, started_at, completed_at, created_at, updated_at
FROM voyages
WHERE id = $1
FOR UPDATE
`

type LockVoyageRowForUpdateRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockVoyageRowForUpdate(ctx context.Context, id pgtype.UUID) (LockVoyageRowForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockVoyageRowForUpdate, id)
	var i LockVoyageRowForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerCurrentVoyage = `-- name: UpdatePlayerCurrentVoyage :exec
UPDATE players
SET current_voyage_id = $1,
    onboarding_completed = true,
    updated_at = transaction_timestamp()
WHERE id = $2
`

type UpdatePlayerCurrentVoyageParams struct {
	VoyageID pgtype.UUID `json:"voyage_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) UpdatePlayerCurrentVoyage(ctx context.Context, arg UpdatePlayerCurrentVoyageParams) error {
	_, err := q.db.Exec(ctx, updatePlayerCurrentVoyage, arg.VoyageID, arg.PlayerID)
	return err
}

const updateVoyageStatus = `-- name: UpdateVoyageStatus :one
UPDATE voyages
SET status = $1,
    completed_at = CASE WHEN $2::boolean
                        THEN transaction_timestamp() ELSE completed_at END,
    row_version = row_version + 1,
    updated_at = transaction_timestamp()
WHERE id = $3
  AND row_version = $4
RETURNING id, public_id, player_id, status, voyage_definition_version_id,
          current_day_number, fund_health, max_fund_health, capital, score,
          row_version, started_at, completed_at, created_at, updated_at
`

type UpdateVoyageStatusParams struct {
	Status       string      `json:"status"`
	SetCompleted bool        `json:"set_completed"`
	ID           pgtype.UUID `json:"id"`
	RowVersion   int64       `json:"row_version"`
}

type UpdateVoyageStatusRow struct {
	ID                        pgtype.UUID        `json:"id"`
	PublicID                  string             `json:"public_id"`
	PlayerID                  pgtype.UUID        `json:"player_id"`
	Status                    string             `json:"status"`
	VoyageDefinitionVersionID pgtype.UUID        `json:"voyage_definition_version_id"`
	CurrentDayNumber          int16              `json:"current_day_number"`
	FundHealth                int32              `json:"fund_health"`
	MaxFundHealth             int32              `json:"max_fund_health"`
	Capital                   int32              `json:"capital"`
	Score                     pgtype.Numeric     `json:"score"`
	RowVersion                int64              `json:"row_version"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateVoyageStatus(ctx context.Context, arg UpdateVoyageStatusParams) (UpdateVoyageStatusRow, error) {
	row := q.db.QueryRow(ctx, updateVoyageStatus,
		arg.Status,
		arg.SetCompleted,
		arg.ID,
		arg.RowVersion,
	)
	var i UpdateVoyageStatusRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PlayerID,
		&i.Status,
		&i.VoyageDefinitionVersionID,
		&i.CurrentDayNumber,
		&i.FundHealth,
		&i.MaxFundHealth,
		&i.Capital,
		&i.Score,
		&i.RowVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
